<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-65186549de95cd2ff331b98fa30c8ceb.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <meta name="author" content="Nicky Wakim">
  <meta name="dcterms.date" content="2025-03-31">
  <title>Categorical Data Analysis – Lesson 2: Introduction to Categorical Data Analysis</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #575f66;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #575f66; } /* Normal */
    code span.al { color: #f51818; background-color: #faefef; font-weight: bold; } /* Alert */
    code span.an { color: #e6ba7e; } /* Annotation */
    code span.at { color: #399ee6; } /* Attribute */
    code span.bn { color: #ff9940; } /* BaseN */
    code span.bu { color: #4cbf99; } /* BuiltIn */
    code span.cf { color: #fa8d3e; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #4cbf99; } /* Char */
    code span.cn { color: #a37acc; } /* Constant */
    code span.co { color: #607880; font-style: italic; } /* Comment */
    code span.cv { color: #a37acc; } /* CommentVar */
    code span.do { color: #607880; } /* Documentation */
    code span.dt { color: #fa8d3e; } /* DataType */
    code span.dv { color: #ff9940; } /* DecVal */
    code span.er { color: #f51818; text-decoration: underline; } /* Error */
    code span.ex { color: #399ee6; font-weight: bold; } /* Extension */
    code span.fl { color: #ff9940; } /* Float */
    code span.fu { color: #f2ae49; } /* Function */
    code span.im { color: #86b300; } /* Import */
    code span.in { color: #ff9940; } /* Information */
    code span.kw { color: #fa8d3e; font-weight: bold; } /* Keyword */
    code span.op { color: #ed9366; } /* Operator */
    code span.ot { color: #55b4d4; } /* Other */
    code span.pp { color: #f07171; } /* Preprocessor */
    code span.re { color: #399ee6; background-color: #ddecf3; } /* RegionMarker */
    code span.sc { color: #4cbf99; } /* SpecialChar */
    code span.ss { color: #4cbf99; } /* SpecialString */
    code span.st { color: #86b300; } /* String */
    code span.va { color: #55b4d4; } /* Variable */
    code span.vs { color: #86b300; } /* VerbatimString */
    code span.wa { color: #f07171; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-879b85e47848f420eaf0aa30a5c8b01f.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#C2352F" class="quarto-title-block center">
  <h1 class="title">Lesson 2: Introduction to Categorical Data Analysis</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Nicky Wakim 
</div>
</div>
</div>

  <p class="date">2025-03-31</p>
</section>
<section id="learning-objectives" class="title-slide slide level1 center">
<h1>Learning Objectives</h1>
<ol type="1">
<li><p>Recognize the motivation for and focus of our course (categorical responses)</p></li>
<li><p>Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation</p></li>
<li><p>Estimate a single proportion</p></li>
<li><p>Estimate a difference in proportions</p></li>
<li><p>Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test</p></li>
<li><p>Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test</p></li>
<li><p>Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test</p></li>
</ol>
</section>

<section>
<section id="learning-objectives-1" class="title-slide slide level1 center">
<h1>Learning Objectives</h1>
<div class="lob">
<ol type="1">
<li>Recognize the motivation for and focus of our course (categorical responses)</li>
</ol>
</div>
<ol start="2" type="1">
<li><p>Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation</p></li>
<li><p>Estimate a single proportion</p></li>
<li><p>Estimate a difference in proportions</p></li>
<li><p>Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test</p></li>
<li><p>Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test</p></li>
<li><p>Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test</p></li>
</ol>
</section>
<section id="what-is-categorical-data-analysis" class="slide level2">
<h2>What is Categorical Data Analysis?</h2>
<ul>
<li><p>In BSTA 512/612 (linear regression), we focused on <span style="color:#70AD47; font-weight: bold;">continuous responses/outcomes</span></p>
<ul>
<li><p>We included <span style="color:#70AD47; font-weight: bold;">categorical variables only as covariates</span> (aka predictors, independent variables, explanatory variables)</p></li>
<li><p>Examples from 512/612: life expectancy (in years), IAT score (ranging from -2 to 2)</p></li>
</ul></li>
</ul>
<p>&nbsp; &nbsp;</p>
<ul>
<li><p>Categorical data analysis focuses on the statistical methods for <span style="color:#4472C4; font-weight: bold;">categorical responses/outcomes</span></p>
<ul>
<li>Explanatory (or ‘independent’) variable can be of any type (continuous or categorical)</li>
</ul></li>
</ul>
</section>
<section id="types-of-variables" class="slide level2">
<h2>Types of Variables</h2>

<img data-src="./images/types_data.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="types-of-variables-outcomes-we-will-cover-in-this-course" class="slide level2">
<h2>Types of Variables: Outcomes we will cover in this course</h2>

<img data-src="./images/types_data_2.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="what-does-this-course-cover" class="slide level2">
<h2>What does this course cover?</h2>
<ul>
<li><p>Strategies for assessing association between categorical response variable and a <span style="color:#70AD47; font-weight: bold;">one explanatory variable</span></p>
<ul>
<li>Hypothesis testing</li>
<li>Measure of association</li>
<li>Simple logistic regression</li>
</ul></li>
</ul>
<p>&nbsp; &nbsp;</p>
<ul>
<li><p>Statistical modeling strategies for assessing association between the categorical response variable and a <span style="color:#4472C4; font-weight: bold;">set of explanatory variables</span></p>
<ul>
<li><p>Logistic regression</p>
<ul>
<li>For binary, ordinal, and multinomial outcomes</li>
</ul></li>
<li><p>Poisson regression</p>
<ul>
<li>For counts outcomes</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="poll-everywhere-question-1" class="slide level2">
<h2>Poll everywhere question 1</h2>
</section></section>
<section>
<section id="learning-objectives-2" class="title-slide slide level1 center">
<h1>Learning Objectives</h1>
<ol type="1">
<li>Recognize the motivation for and focus of our course (categorical responses)</li>
</ol>
<div class="lob">
<ol start="2" type="1">
<li>Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation</li>
</ol>
</div>
<ol start="3" type="1">
<li><p>Estimate a single proportion</p></li>
<li><p>Estimate a difference in proportions</p></li>
<li><p>Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test</p></li>
<li><p>Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test</p></li>
<li><p>Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test</p></li>
</ol>
</section>
<section id="binomial-distribution" class="slide level2">
<h2>Binomial Distribution</h2>
<ul>
<li><p>Consider a sample of <span class="math inline">\(n\)</span> independent trials, each of which can have only two possible outcomes (“success” and “failure”)</p></li>
<li><p>For each trial: <span class="math display">\[\begin{align} P( \text{success}) &amp; = p \\
                  P( \text{failure}) &amp; = 1- p = q \end{align}\]</span></p></li>
<li><p><strong>Binomial distribution:</strong> distribution of the number of successes in n independent trials</p></li>
<li><p>The probability mass function for the binomial distribution is: <span class="math display">\[P(X=k) = {n \choose k} p^k q^{n-k}, \text{ for } k = 0, 1, ..., n\]</span></p>
<ul>
<li><span class="math inline">\(E(X) = np\)</span></li>
<li><span class="math inline">\(Var(X) = npq = np(1-p)\)</span></li>
</ul></li>
</ul>
</section>
<section id="binomial-distribution-1" class="slide level2">
<h2>Binomial Distribution</h2>
<ul>
<li><p>Consider a sample of <span class="math inline">\(n\)</span> independent trials, each of which can have only two possible outcomes (“success” and “failure”)</p></li>
<li><p>For each trial: <span class="math display">\[\begin{align} P( \text{success}) &amp; = p \\
                  P( \text{failure}) &amp; = 1- p = q \end{align}\]</span></p></li>
<li><p><strong>Binomial distribution:</strong> distribution of the number of successes in n independent trials</p></li>
<li><p>The probability mass function for the binomial distribution is: <span class="math display">\[P(X=k) = {n \choose k} p^k q^{n-k}, \text{ for } k = 0, 1, ..., n\]</span></p>
<ul>
<li><span class="math inline">\(E(X) = np\)</span></li>
<li><span class="math inline">\(Var(X) = npq = np(1-p)\)</span></li>
</ul></li>
</ul>
<p><img data-src="./images/binomial_q.png" class="absolute" style="top: 70%; right: 5%; width: 800px; "></p>
</section>
<section id="binomial-distribution-r-commands" class="slide level2">
<h2>Binomial Distribution: R commands</h2>
<p>R commands with their <span style="color:#70AD47">input</span> and <span style="color:#4472C4">output</span>:</p>
<table class="caption-top">
<colgroup>
<col style="width: 27%">
<col style="width: 72%">
</colgroup>
<thead>
<tr class="header">
<th>R code</th>
<th>What does it return?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>rbinom()</code></td>
<td>returns <span style="color:#4472C4">sample of random variables</span> with <span style="color:#70AD47">specified binomial distribution</span></td>
</tr>
<tr class="even">
<td><code>dbinom()</code></td>
<td>returns <span style="color:#4472C4">probability</span> of getting <span style="color:#70AD47">certain number of successes</span></td>
</tr>
<tr class="odd">
<td><code>pbinom()</code></td>
<td>returns <span style="color:#4472C4">cumulative probability</span> of getting <span style="color:#70AD47">certain number or less</span> successes</td>
</tr>
<tr class="even">
<td><code>qbinom()</code></td>
<td>returns <span style="color:#4472C4">number of successes</span> corresponding to <span style="color:#70AD47">desired quantile</span></td>
</tr>
</tbody>
</table>
</section>
<section id="binomial-distribution-example" class="slide level2">
<h2>Binomial Distribution Example</h2>
<div class="example">
<div class="ex-title">
<p>Example</p>
</div>
<div class="ex-cont">
<p>If the probability that one white blood cell is a lymphocyte is 0.2, compute the probability of 2 lymphocytes out of 10 white blood cells</p>
</div>
</div>
<p><span class="math display">\[P(X=2) = {10 \choose 2} 0.2^2 (1-0.2)^{10-2}  = 0.3020\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">dbinom</span>(<span class="dv">2</span>, <span class="dv">10</span>, <span class="fl">0.2</span>) <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.302</code></pre>
</div>
</div>
</section>
<section id="normal-approximation-of-the-binomial-distribution" class="slide level2">
<h2>Normal Approximation of the Binomial Distribution</h2>
<ul>
<li><p>Also known as: <strong>Sampling distribution of</strong> <span class="math inline">\(\widehat{p}\)</span></p></li>
<li><p>IF <span class="math inline">\(X\sim \text{Binomial}(n,p)\)</span> and <span class="math inline">\(np&gt;10\)</span> and <span class="math inline">\(nq = n(1-p) &gt; 10\)</span></p>
<ul>
<li>Ensures sample size (<span class="math inline">\(n\)</span>) is moderately large and the <span class="math inline">\(p\)</span> is not too close to 0 or 1</li>
<li>Other resources use other criteria (like <span class="math inline">\(npq&gt;5\)</span> or <span class="math inline">\(np&gt;5\)</span>)</li>
<li>When looking at a sample, we use <span class="math inline">\(\widehat{p}\)</span> instead of <span class="math inline">\(p\)</span> to check this!!</li>
</ul></li>
</ul>
<p>&nbsp;</p>
<ul>
<li><p>THEN approximately <span class="math inline">\(𝑋\sim \text{Normal}\big(\mu_X = np, \sigma_X = \sqrt{np(1-p)} \big)\)</span></p>
<ul>
<li>Or we often write this as the sampling distribution of <span class="math inline">\(\widehat{p}\)</span>: <span class="math display">\[\widehat{p} \sim \text{Normal}\bigg(\mu_{\widehat{p}} = p, \sigma_{\widehat{p}} = \sqrt{\dfrac{p(1-p)}{n}}\bigg)\]</span></li>
</ul></li>
<li><p><a href="https://www.youtube.com/watch?v=CCqWkJ_pqNU&amp;ab_channel=jbstatistics">Pretty good video behind the intuition of this</a> (Watch 00:00 - 05:40)</p></li>
</ul>
</section>
<section id="different-tests-of-association" class="slide level2">
<h2>Different tests of association</h2>

<img data-src="./images/test_organization.png" class="quarto-figure quarto-figure-center r-stretch"></section></section>
<section>
<section id="learning-objectives-3" class="title-slide slide level1 center">
<h1>Learning Objectives</h1>
<ol type="1">
<li><p>Recognize the motivation for and focus of our course (categorical responses)</p></li>
<li><p>Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation</p></li>
</ol>
<div class="lob">
<ol start="3" type="1">
<li>Estimate a single proportion</li>
</ol>
</div>
<ol start="4" type="1">
<li><p>Estimate a difference in proportions</p></li>
<li><p>Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test</p></li>
<li><p>Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test</p></li>
<li><p>Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test</p></li>
</ol>
</section>
<section id="estimate-and-confidence-interval-of-single-proportion" class="slide level2">
<h2>Estimate and Confidence Interval of Single Proportion</h2>
<ul>
<li>Estimate of proportion:</li>
</ul>
<p><span class="math display">\[
\widehat{p} = \dfrac{\# \text{successes}}{\# \text{successes} + \# \text{failures}}
\]</span></p>
<ul>
<li><p>Use the sampling distribution of <span class="math inline">\(\widehat{p}\)</span> to construct the confidence interval:</p>
<ul>
<li><span class="math inline">\((1-\alpha)\%\)</span> confidence interval for estimate proportion:</li>
</ul></li>
</ul>
<p><span class="math display">\[\begin{align} \widehat{p} &amp;\pm z^*_{(1-\alpha/2)} \cdot SE_{\hat{p}} \\ \widehat{p} &amp;\pm z^*_{(1-\alpha/2)} \cdot \sqrt{\frac{\hat{p}(1-\hat{p})}{n}} \end{align}\]</span></p>
<ul>
<li>Using <span class="math inline">\(SE_{\hat{p}} = \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\)</span> - instead of <span class="math inline">\(\sigma_{p} = \sqrt{\frac{p(1-p)}{n}}\)</span> - because we don’t know exactly what <span class="math inline">\(p\)</span> is</li>
</ul>
</section>
<section id="section" class="slide level2">
<h2></h2>
<div class="example">
<div class="ex-title">
<p>Smoking status example</p>
</div>
<div class="ex-cont">
<p>A cross-sectional study of 8681 patients was conducted to evaluate the nature of smoking status among people. Of the 8681 people, 4840 were nonsmokers and 3841 were smokers.</p>
</div>
</div>
<p><strong>Needed steps:</strong></p>
<ol type="1">
<li>Estimate proportion <span class="math inline">\(\widehat{p}\)</span></li>
<li>Check that <span class="math inline">\(n\widehat{p}&gt;10\)</span> and <span class="math inline">\(n(1-\widehat{p})&gt;10\)</span> in order to make normal approximation</li>
<li>Construct 95% confidence interval</li>
<li>Write interpretation</li>
</ol>
</section>
<section id="section-1" class="slide level2 smaller">
<h2></h2>
<div class="example">
<div class="ex-title">
<p>Smoking status example</p>
</div>
<div class="ex-cont">
<p>A cross-sectional study of 8681 patients was conducted to evaluate the nature of smoking status among people. Of the 8681 people, 4840 were nonsmokers and 3841 were smokers.</p>
</div>
</div>
<div class="columns">
<div class="column">
<ol type="1">
<li>Estimate proportion <span class="math inline">\(\widehat{p}\)</span> <span class="math display">\[ \widehat{p} = \dfrac{3841}{3841 + 4840} = \dfrac{3841}{8681} = 0.44246\]</span></li>
<li>Check that <span class="math inline">\(n\widehat{p}&gt;10\)</span> and <span class="math inline">\(n(1-\widehat{p})&gt;10\)</span> in order to make normal approximation <span class="math display">\[ n\widehat{p} = 8681\cdot0.4425 = 3841 &gt; 10\]</span> <span class="math display">\[ n(1-\widehat{p}) = 8681\cdot(1-0.4425) = 4840 &gt; 10\]</span></li>
</ol>
</div><div class="column">
<ol start="3" type="1">
<li>Construct 95% confidence interval</li>
</ol>
<p><span class="math display">\[ \widehat{p} \pm z^*_{0.975} \cdot \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="dv">3841</span>, <span class="at">n =</span> <span class="dv">8681</span>, <span class="at">correct =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1-sample proportions test with continuity correction

data:  3841 out of 8681, null probability 0.5
X-squared = 114.73, df = 1, p-value &lt; 2.2e-16
alternative hypothesis: true p is not equal to 0.5
95 percent confidence interval:
 0.4319827 0.4529896
sample estimates:
        p 
0.4424605 </code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Write interpretation of <strong>estimate</strong></li>
</ol>
<p>The estimated proportion of smokers is 0.442 (95% CI: 0.432, 0.453).</p>
<p>Additional interpretation of CI: We are 95% confident that the (population) proportion of smokers is between 0.432 and 0.453.</p>
</div></div>
</section>
<section id="poll-everywhere-question-2" class="slide level2">
<h2>Poll everywhere question 2</h2>
</section></section>
<section>
<section id="learning-objectives-4" class="title-slide slide level1 center">
<h1>Learning Objectives</h1>
<ol type="1">
<li><p>Recognize the motivation for and focus of our course (categorical responses)</p></li>
<li><p>Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation</p></li>
<li><p>Estimate a single proportion</p></li>
</ol>
<div class="lob">
<ol start="4" type="1">
<li>Estimate a difference in proportions</li>
</ol>
</div>
<ol start="5" type="1">
<li><p>Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test</p></li>
<li><p>Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test</p></li>
<li><p>Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test</p></li>
</ol>
</section>
<section id="estimate-and-confidence-interval-for-difference-in-proportions" class="slide level2">
<h2>Estimate and Confidence Interval for Difference in Proportions</h2>
<ul>
<li><p>Use the sampling distribution of <span class="math inline">\(\widehat{p}_1\)</span> and <span class="math inline">\(\widehat{p}_2\)</span> to construct the confidence interval:</p>
<ul>
<li><span class="math inline">\((1-\alpha)\%\)</span> confidence interval for estimate difference in proportions:</li>
</ul></li>
</ul>
<p><span class="math display">\[\begin{align} \widehat{p}_1 - \widehat{p}_2 &amp;\pm z^*_{(1-\alpha/2)} \cdot SE_{\hat{p}_1 - \hat{p}_2} \\ \widehat{p}_1 - \widehat{p}_2 &amp;\pm z^*_{(1-\alpha/2)} \cdot \sqrt{
\frac{\hat{p}_1\cdot(1-\hat{p}_1)}{n_1} + \frac{\hat{p}_2\cdot(1-\hat{p}_2)}{n_2}} \end{align}\]</span></p>
<ul>
<li>Using <span class="math inline">\(SE_{\hat{p}_1 - \hat{p}_2} = \sqrt{\frac{\hat{p}_1\cdot(1-\hat{p}_1)}{n_1} + \frac{\hat{p}_2\cdot(1-\hat{p}_2)}{n_2}}\)</span> because we don’t know exactly what <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span> are</li>
</ul>
</section>
<section id="poll-everywhere-question-3" class="slide level2">
<h2>Poll Everywhere Question 3</h2>
</section>
<section id="example-strong-heart-study-12" class="slide level2">
<h2>Example: Strong Heart Study (1/2)</h2>
<div class="columns">
<div class="column" style="width:65%;">
<p>The <a href="https://strongheartstudy.org/">Strong Heart Study</a> is an ongoing study of American Indians residing in 13 tribal communities in three geographic areas (AZ, OK, and SD/ND) to study prevalence and incidence of cardiovascular disease and to identify risk factors. We will be examining the 4-year cumulative incidence of diabetes with one risk factor, glucose tolerance.</p>
<p>&nbsp;</p>
<ul>
<li><p><strong>Impaired glucose:</strong> normal or impaired glucose tolerance at baseline visit (between 1988 and 1991)</p>
<p>&nbsp;</p></li>
<li><p><strong>Diabetes:</strong> Indicator of diabetes at follow-up visit (roughly four years after baseline) according to two-hour oral glucose tolerance test</p></li>
</ul>
</div><div class="column" style="width:35%;">
<p><img data-src="./images/home_box3.png" width="500"></p>
</div></div>
</section>
<section id="example-strong-heart-study-22" class="slide level2">
<h2>Example: Strong Heart Study (2/2)</h2>
<p>There is a total of 1664 American Indians in the dataset, with the following distribution of folks with diabetes and glucose tolerance:</p>
<p>&nbsp;</p>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="co">#shs_data = read.csv(file = here("./data/SHS_data.csv"))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a>SHS <span class="ot">=</span> <span class="fu">tibble</span>(<span class="at">Diabetes =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"Not diabetic"</span>, </span>
<span id="cb6-2"><a></a>                   <span class="dv">1338</span>), </span>
<span id="cb6-3"><a></a>                   <span class="fu">rep</span>(<span class="st">"Diabetic"</span>, <span class="dv">326</span>)),</span>
<span id="cb6-4"><a></a>              <span class="at">Glucose =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"Normal"</span>, </span>
<span id="cb6-5"><a></a>                  <span class="dv">1004</span>),<span class="co">#Not diabetic</span></span>
<span id="cb6-6"><a></a>          <span class="fu">rep</span>(<span class="st">"Impaired"</span>, <span class="dv">334</span>),</span>
<span id="cb6-7"><a></a>          <span class="fu">rep</span>(<span class="st">"Normal"</span>, </span>
<span id="cb6-8"><a></a>              <span class="dv">128</span>), <span class="co">#Diabetic</span></span>
<span id="cb6-9"><a></a>          <span class="fu">rep</span>(<span class="st">"Impaired"</span>, <span class="dv">198</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div><div class="column" style="width:40%;">
<div class="cell">
<details class="code-fold">
<summary>Displaying the contingency table in R</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a>SHS <span class="sc">%&gt;%</span> <span class="fu">tabyl</span>(Glucose, Diabetes) <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a></a>  <span class="fu">adorn_totals</span>(<span class="at">where =</span> <span class="fu">c</span>(<span class="st">"row"</span>, <span class="st">"col"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a></a>  <span class="fu">gt</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb7-4"><a></a>  <span class="fu">tab_stubhead</span>(<span class="at">label =</span> <span class="st">"Glucose Impairment"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-5"><a></a>  <span class="fu">tab_spanner</span>(<span class="at">label =</span> <span class="st">"Diabetes"</span>, </span>
<span id="cb7-6"><a></a>              <span class="at">columns =</span> <span class="fu">c</span>(<span class="st">"Not diabetic"</span>, <span class="st">"Diabetic"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb7-7"><a></a>  <span class="fu">tab_options</span>(<span class="at">table.font.size =</span> <span class="dv">45</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="vgkinixnmj" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#vgkinixnmj table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#vgkinixnmj thead, #vgkinixnmj tbody, #vgkinixnmj tfoot, #vgkinixnmj tr, #vgkinixnmj td, #vgkinixnmj th {
  border-style: none;
}

#vgkinixnmj p {
  margin: 0;
  padding: 0;
}

#vgkinixnmj .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 45px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#vgkinixnmj .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#vgkinixnmj .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#vgkinixnmj .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#vgkinixnmj .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#vgkinixnmj .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#vgkinixnmj .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#vgkinixnmj .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#vgkinixnmj .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#vgkinixnmj .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#vgkinixnmj .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#vgkinixnmj .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#vgkinixnmj .gt_spanner_row {
  border-bottom-style: hidden;
}

#vgkinixnmj .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#vgkinixnmj .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#vgkinixnmj .gt_from_md > :first-child {
  margin-top: 0;
}

#vgkinixnmj .gt_from_md > :last-child {
  margin-bottom: 0;
}

#vgkinixnmj .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#vgkinixnmj .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#vgkinixnmj .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#vgkinixnmj .gt_row_group_first td {
  border-top-width: 2px;
}

#vgkinixnmj .gt_row_group_first th {
  border-top-width: 2px;
}

#vgkinixnmj .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#vgkinixnmj .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#vgkinixnmj .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#vgkinixnmj .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#vgkinixnmj .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#vgkinixnmj .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#vgkinixnmj .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#vgkinixnmj .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#vgkinixnmj .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#vgkinixnmj .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#vgkinixnmj .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#vgkinixnmj .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#vgkinixnmj .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#vgkinixnmj .gt_left {
  text-align: left;
}

#vgkinixnmj .gt_center {
  text-align: center;
}

#vgkinixnmj .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#vgkinixnmj .gt_font_normal {
  font-weight: normal;
}

#vgkinixnmj .gt_font_bold {
  font-weight: bold;
}

#vgkinixnmj .gt_font_italic {
  font-style: italic;
}

#vgkinixnmj .gt_super {
  font-size: 65%;
}

#vgkinixnmj .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#vgkinixnmj .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#vgkinixnmj .gt_indent_1 {
  text-indent: 5px;
}

#vgkinixnmj .gt_indent_2 {
  text-indent: 10px;
}

#vgkinixnmj .gt_indent_3 {
  text-indent: 15px;
}

#vgkinixnmj .gt_indent_4 {
  text-indent: 20px;
}

#vgkinixnmj .gt_indent_5 {
  text-indent: 25px;
}

#vgkinixnmj .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#vgkinixnmj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="gt_col_headings gt_spanner_row header">
<th rowspan="2" id="Glucose" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Glucose</th>
<th colspan="2" id="Diabetes" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" scope="colgroup"><div class="gt_column_spanner">
Diabetes
</div></th>
<th rowspan="2" id="Total" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Total</th>
</tr>
<tr class="gt_col_headings even">
<th id="Not-diabetic" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Not diabetic</th>
<th id="Diabetic" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Diabetic</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Glucose">Impaired</td>
<td class="gt_row gt_right" headers="Not diabetic">334</td>
<td class="gt_row gt_right" headers="Diabetic">198</td>
<td class="gt_row gt_right" headers="Total">532</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Glucose">Normal</td>
<td class="gt_row gt_right" headers="Not diabetic">1004</td>
<td class="gt_row gt_right" headers="Diabetic">128</td>
<td class="gt_row gt_right" headers="Total">1132</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Glucose">Total</td>
<td class="gt_row gt_right" headers="Not diabetic">1338</td>
<td class="gt_row gt_right" headers="Diabetic">326</td>
<td class="gt_row gt_right" headers="Total">1664</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div></div>
</section>
<section id="section-2" class="slide level2">
<h2></h2>
<div class="example">
<div class="ex-title">
<p>Strong Heart Study</p>
</div>
<div class="ex-cont">
<p>What is the difference in proportions for American Indians that have diabetes comparing individuals with normal vs.&nbsp;impaired glucose?</p>
</div>
</div>
<p><strong>Needed steps:</strong></p>
<ol type="1">
<li>Estimate the difference in proportions</li>
<li>Check that each cell has at least 10 individuals</li>
<li>Construct 95% confidence interval</li>
<li>Write interpretation of estimate</li>
</ol>
</section>
<section id="section-3" class="slide level2 smaller">
<h2></h2>
<div class="example">
<div class="ex-title">
<p>Strong Heart Study</p>
</div>
<div class="ex-cont">
<p>What is the difference in proportions for American Indians that have diabetes comparing individuals with normal vs.&nbsp;impaired glucose?</p>
</div>
</div>
<div class="columns">
<div class="column">
<div class="cell">
<div class="cell-output-display">
<div id="kwxkabbizi" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#kwxkabbizi table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#kwxkabbizi thead, #kwxkabbizi tbody, #kwxkabbizi tfoot, #kwxkabbizi tr, #kwxkabbizi td, #kwxkabbizi th {
  border-style: none;
}

#kwxkabbizi p {
  margin: 0;
  padding: 0;
}

#kwxkabbizi .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 28px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#kwxkabbizi .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#kwxkabbizi .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#kwxkabbizi .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#kwxkabbizi .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#kwxkabbizi .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kwxkabbizi .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#kwxkabbizi .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#kwxkabbizi .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#kwxkabbizi .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#kwxkabbizi .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#kwxkabbizi .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#kwxkabbizi .gt_spanner_row {
  border-bottom-style: hidden;
}

#kwxkabbizi .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#kwxkabbizi .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#kwxkabbizi .gt_from_md > :first-child {
  margin-top: 0;
}

#kwxkabbizi .gt_from_md > :last-child {
  margin-bottom: 0;
}

#kwxkabbizi .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#kwxkabbizi .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#kwxkabbizi .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#kwxkabbizi .gt_row_group_first td {
  border-top-width: 2px;
}

#kwxkabbizi .gt_row_group_first th {
  border-top-width: 2px;
}

#kwxkabbizi .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#kwxkabbizi .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#kwxkabbizi .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#kwxkabbizi .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kwxkabbizi .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#kwxkabbizi .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#kwxkabbizi .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#kwxkabbizi .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#kwxkabbizi .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kwxkabbizi .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#kwxkabbizi .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#kwxkabbizi .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#kwxkabbizi .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#kwxkabbizi .gt_left {
  text-align: left;
}

#kwxkabbizi .gt_center {
  text-align: center;
}

#kwxkabbizi .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#kwxkabbizi .gt_font_normal {
  font-weight: normal;
}

#kwxkabbizi .gt_font_bold {
  font-weight: bold;
}

#kwxkabbizi .gt_font_italic {
  font-style: italic;
}

#kwxkabbizi .gt_super {
  font-size: 65%;
}

#kwxkabbizi .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#kwxkabbizi .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#kwxkabbizi .gt_indent_1 {
  text-indent: 5px;
}

#kwxkabbizi .gt_indent_2 {
  text-indent: 10px;
}

#kwxkabbizi .gt_indent_3 {
  text-indent: 15px;
}

#kwxkabbizi .gt_indent_4 {
  text-indent: 20px;
}

#kwxkabbizi .gt_indent_5 {
  text-indent: 25px;
}

#kwxkabbizi .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#kwxkabbizi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="gt_col_headings gt_spanner_row header">
<th rowspan="2" id="Glucose" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Glucose</th>
<th colspan="2" id="Diabetes" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" scope="colgroup"><div class="gt_column_spanner">
Diabetes
</div></th>
<th rowspan="2" id="Total" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Total</th>
</tr>
<tr class="gt_col_headings even">
<th id="Not-diabetic" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Not diabetic</th>
<th id="Diabetic" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Diabetic</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Glucose">Impaired</td>
<td class="gt_row gt_right" headers="Not diabetic">334</td>
<td class="gt_row gt_right" headers="Diabetic">198</td>
<td class="gt_row gt_right" headers="Total">532</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Glucose">Normal</td>
<td class="gt_row gt_right" headers="Not diabetic">1004</td>
<td class="gt_row gt_right" headers="Diabetic">128</td>
<td class="gt_row gt_right" headers="Total">1132</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Glucose">Total</td>
<td class="gt_row gt_right" headers="Not diabetic">1338</td>
<td class="gt_row gt_right" headers="Diabetic">326</td>
<td class="gt_row gt_right" headers="Total">1664</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<ol type="1">
<li><p>Estimate the difference in proportions <span class="math display">\[ \widehat{p}_1 -\widehat{p}_2 = \dfrac{198}{532} - \dfrac{128}{1132} = 0.2591\]</span></p></li>
<li><p>Check that each cell has at least 10 individuals</p></li>
</ol>
</div><div class="column">
<ol start="3" type="1">
<li>Construct 95% confidence interval</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="fu">table</span>(SHS<span class="sc">$</span>Glucose, SHS<span class="sc">$</span>Diabetes), </span>
<span id="cb8-2"><a></a>          <span class="at">correct =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  table(SHS$Glucose, SHS$Diabetes)
X-squared = 152.6, df = 1, p-value &lt; 2.2e-16
alternative hypothesis: two.sided
95 percent confidence interval:
 0.2126963 0.3055162
sample estimates:
   prop 1    prop 2 
0.3721805 0.1130742 </code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Write interpretation of <strong>estimate</strong></li>
</ol>
<p>The estimated difference in proportion of diabetic American Indians comparing is 0.259 (95% CI: 0.213, 0.306).</p>
<p>Additional interpretation of CI: We are 95% confident that the difference in (population) proportions of American Indians who have normal glucose tolerance and impaired glucose tolerance that developed diabetes is between 0.213 and 0.306.</p>
</div></div>
</section>
<section id="mcnemars-test" class="slide level2">
<h2>McNemar’s Test</h2>
<ul>
<li>McNemar’s test should be used if data is from a matched pairs study</li>
</ul>
<p>&nbsp;</p>
<ul>
<li><p>What is a matched-pairs study?</p>
<ul>
<li>Participants are paired based on key characteristics</li>
<li>Each participant within a pair will be assigned to different treatment groups</li>
</ul></li>
<li><p>Categorical test that is parallel to the “paired t-test”</p></li>
</ul>
<p>&nbsp;</p>
<ul>
<li><p>R packages and functions</p>
<ul>
<li>Normal approximation: <code>mcnemar.test()</code> in built-in <code>stats</code> package</li>
<li>Exact test: <code>mcnemar.exact()</code> in <code>exact2x2</code> package</li>
</ul></li>
</ul>
<p>&nbsp;</p>
<ul>
<li><strong>If you would like more information of McNemar’s test, please see Rosner TB: 10.4 and 10.5: Paired Samples</strong></li>
</ul>
</section>
<section id="summary-so-far" class="slide level2">
<h2>Summary so far</h2>
<ul>
<li>Introduced categorical data as the response in analysis</li>
<li>Reviewed an important distribution (Binomial distribution) for categorical data analysis</li>
<li>Estimated a single proportion from a sample with its confidence interval</li>
<li>Estimated a difference in proportions from a sample with its confidence interval</li>
</ul>
<p>&nbsp; &nbsp;</p>
<ul>
<li><p>Can we expand this to ask a more general question about association between a response and explanatory variable?</p>
<ul>
<li>What if there is more than 2 categories for either variable?</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="learning-objectives-5" class="title-slide slide level1 center">
<h1>Learning Objectives</h1>
<ol type="1">
<li><p>Recognize the motivation for and focus of our course (categorical responses)</p></li>
<li><p>Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation</p></li>
<li><p>Estimate a single proportion</p></li>
<li><p>Estimate a difference in proportions</p></li>
</ol>
<div class="lob">
<ol start="5" type="1">
<li>Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables</li>
</ol>
</div>
<ol start="6" type="1">
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test</p></li>
<li><p>Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test</p></li>
<li><p>Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test</p></li>
</ol>
</section>
<section id="contingency-tables-r-x-c" class="slide level2">
<h2>Contingency Tables (R x C)</h2>
<ul>
<li><p>R X C contingency tables</p>
<ul>
<li><p>Contains information for two discrete variables: one has R categories and the other has C categories.</p></li>
<li><p>Refers to the number of rows (R) and number of columns (C) in the table</p></li>
</ul></li>
</ul>
<p>&nbsp;</p>
<ul>
<li><p>For two proportions: focused on 2 X 2 contingency tables</p>
<ul>
<li>R = 2, C = 2</li>
</ul></li>
</ul>
<p>&nbsp;</p>
<ul>
<li><p>Expand our contingency tables to variables with 2 or more categories</p>
<ul>
<li>Categories can be ordinal or nominal</li>
</ul></li>
</ul>
</section>
<section id="contingency-table-example" class="slide level2">
<h2>Contingency Table: Example</h2>
<p>Let’s say we are interested in learning the association between the development of breast cancer and age at first birth. Our first step is typically to present the observed data:</p>

<img data-src="./images/Conting_tab_ex.png" class="quarto-figure quarto-figure-center r-stretch" width="511"><ul>
<li>This is a 2 x 5 contingency table</li>
</ul>
</section>
<section id="test-associationtrend-of-r-x-c-contingency-table" class="slide level2">
<h2>Test Association/Trend of R X C Contingency Table</h2>
<p>&nbsp;</p>
<div class="columns">
<div class="column" style="width:46%;">
<p>If <span style="color:#4472C4; font-weight: bold;">both variables are nominal</span>, a <span style="color:#4472C4; font-style: italic;">test of general association</span> will be sufficient</p>
<ul>
<li><p>Test of general association is the same regardless of R and C</p></li>
<li><p>Test used for 2x2 contingency table same as 5x3 contingency table</p></li>
<li><p>We will cover:</p>
<ul>
<li>Chi-squared test</li>
<li>Fisher Exact test</li>
</ul></li>
</ul>
</div><div class="column" style="width:6%;">

</div><div class="column" style="width:48%;">
<p>If <span style="color:#70AD47; font-weight: bold;">one or both variables are ordinal</span>, a <span style="color:#70AD47; font-style: italic;">test of trend</span> may be of interest</p>
<ul>
<li><p>Treats ordinal variables as quantitative rather than qualitative (nominal scale)</p></li>
<li><p>Test of trend has greater power than the test of general association</p></li>
<li><p>We will cover:</p>
<ul>
<li>Cochran-Armitage test</li>
<li>Mantel-Haenszel test</li>
</ul></li>
</ul>
</div></div>
</section>
<section id="poll-everywhere-question-4" class="slide level2">
<h2>Poll Everywhere Question 4</h2>
</section>
<section id="test-of-general-association" class="slide level2">
<h2>Test of General Association</h2>
<ul>
<li><strong>General research question:</strong> Are two variables (both categorical, nominal) associated with each other?</li>
</ul>
<p>&nbsp;</p>
<ul>
<li><p>Translated to a hypothesis test:</p>
<ul>
<li><span class="math inline">\(H_0\)</span> : There is no association between the two variables / The variables are independent</li>
<li><span class="math inline">\(H_1\)</span> : There is an association between the two variables / The variables are not independent</li>
</ul></li>
</ul>
<p>&nbsp; &nbsp;</p>
<ul>
<li><p>We have two options for testing general association:</p>
<ol type="1">
<li>Chi-squared test</li>
<li>Fisher’s Exact test</li>
</ol></li>
</ul>
</section>
<section id="test-of-general-association-shs-example" class="slide level2">
<h2>Test of General Association: SHS Example</h2>
<ul>
<li><p><strong>Main question:</strong> Do American Indians with impaired glucose tolerance have a different incidence of diabetes?</p>
<ul>
<li>Is glucose tolerance associated with diabetes incidence among American Indians?</li>
</ul></li>
<li><p>We have two variables, and both variables have two nominal categories</p>
<ul>
<li>Diabetes outcome: Not diabetic and Diabetic</li>
<li>Glucose tolerance: Normal or Impaired</li>
</ul></li>
</ul>
<p>&nbsp;</p>
<ul>
<li><p>Answer research question with a test of general association</p></li>
<li><p>Hypothesis:</p>
<ul>
<li><span class="math inline">\(H_0\)</span> : There is no association between glucose tolerance and diabetes / Glucose tolerance and diabetes are independent</li>
<li><span class="math inline">\(H_1\)</span> : There is an association between glucose tolerance and diabetes / Glucose tolerance and diabetes are not independent</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="learning-objectives-6" class="title-slide slide level1 center">
<h1>Learning Objectives</h1>
<ol type="1">
<li><p>Recognize the motivation for and focus of our course (categorical responses)</p></li>
<li><p>Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation</p></li>
<li><p>Estimate a single proportion</p></li>
<li><p>Estimate a difference in proportions</p></li>
<li><p>Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables</p></li>
</ol>
<div class="lob">
<ol start="6" type="1">
<li>Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test</li>
</ol>
</div>
<ol start="7" type="1">
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test</p></li>
<li><p>Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test</p></li>
<li><p>Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test</p></li>
</ol>
</section>
<section id="chi-squared-test" class="slide level2">
<h2>Chi-squared test</h2>
<ul>
<li>Test to see how likely is it that we observe our data given the null hypothesis (no association)</li>
</ul>
<p>&nbsp;</p>
<ul>
<li>We use the null to calculate the expected cell counts and compare them to the observed cell counts</li>
</ul>
<p>&nbsp;</p>
<ul>
<li><p>Requirements to conduct Chi-squared test (expected cell counts)</p>
<ul>
<li><p>For 2 x 2 contingency table:</p>
<ul>
<li>No expected cell counts should be less than 10</li>
</ul></li>
<li><p>For contingency table with 3x2, 3x3, 4x4, etc.:</p>
<ul>
<li>No more than 20% of expected cell counts are less than 5</li>
<li>No expected cell counts are less than 1</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="chi-squared-test-process" class="slide level2">
<h2>Chi-squared test: Process</h2>
<ol type="1">
<li><p>Check that the <span style="color:#70AD47"><strong>expected cell counts</strong></span> threshold is met</p></li>
<li><p>Set the <span style="color:#70AD47"><strong>level of significance</strong></span> <span class="math inline">\(\alpha\)</span></p></li>
<li><p>Specify the <span style="color:#70AD47"><strong>null</strong></span> ( <span class="math inline">\(H_0\)</span> ) and <span style="color:#70AD47"><strong>alternative</strong></span> ( <span class="math inline">\(H_A\)</span> ) <span style="color:#70AD47"><strong>hypotheses</strong></span></p>
<ul>
<li>In symbols</li>
<li>In words</li>
<li>Alternative: one- or two-sided?</li>
</ul></li>
<li><p>Calculate the <span style="color:#70AD47"><strong>test statistic</strong></span> and <span style="color:#70AD47"><strong>p-value</strong></span> for Chi-squared test in R</p>
<ul>
<li>We will not discuss the test statistic’s equation</li>
</ul></li>
<li><p>Write a <span style="color:#70AD47"><strong>conclusion</strong></span> to the hypothesis test</p>
<ul>
<li>Do we reject or fail to reject <span class="math inline">\(H_0\)</span>?</li>
<li>Write a conclusion in the context of the problem</li>
</ul></li>
</ol>
</section>
<section id="chi-squared-test-expected-cell-counts" class="slide level2">
<h2>Chi-squared test: Expected Cell Counts</h2>
<ul>
<li>Is the sample size big enough for the chi-square test to be adequate? What are the expected cell counts?</li>
</ul>
<p>&nbsp;</p>
<ul>
<li>If you want an explanation of how to calculate by hand, please see Vu and Harringtion TB (section 8.3.1, page 405)</li>
</ul>
<p>&nbsp;</p>
<ul>
<li>Too time consuming for this class, but R does it quickly using the <code>expected()</code> function in the <code>epitools</code> package</li>
</ul>
</section>
<section id="chi-squared-test-expected-cell-counts-1" class="slide level2">
<h2>Chi-squared test: Expected Cell Counts</h2>
<ul>
<li>In the Strong Heart Study…</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a>SHS_table <span class="ot">=</span> <span class="fu">table</span>(SHS<span class="sc">$</span>Glucose, SHS<span class="sc">$</span>Diabetes)</span>
<span id="cb10-2"><a></a>SHS_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
           Diabetic Not diabetic
  Impaired      198          334
  Normal        128         1004</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a><span class="fu">library</span>(epitools)</span>
<span id="cb12-2"><a></a><span class="fu">expected</span>(SHS_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
           Diabetic Not diabetic
  Impaired  104.226      427.774
  Normal    221.774      910.226</code></pre>
</div>
</div>
<p>&nbsp;</p>
<div class="columns">
<div class="column" style="width:15%;">

</div><div class="column" style="width:28%;">
<div class="hl3">
<p>All expected counts &gt; 5</p>
</div>
</div><div class="column" style="width:38%;">

</div></div>
</section>
<section id="chi-squared-test-shs-example" class="slide level2">
<h2>Chi-squared test: SHS Example</h2>
<div class="columns">
<div class="column">
<ol type="1">
<li>Check expected cell counts threshold</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a><span class="fu">expected</span>(SHS_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
           Diabetic Not diabetic
  Impaired  104.226      427.774
  Normal    221.774      910.226</code></pre>
</div>
</div>
<p>All expected cells are greater than 5.</p>
<ol start="2" type="1">
<li><p><span class="math inline">\(\alpha = 0.05\)</span></p></li>
<li><p>Hypothesis test:</p>
<ul>
<li><span class="math inline">\(H_0\)</span> : There is no association between glucose tolerance and diabetes</li>
<li><span class="math inline">\(H_1\)</span> : There is an association between glucose tolerance and diabetes</li>
</ul></li>
</ol>
</div><div class="column">
<ol start="4" type="1">
<li>Calculate the test statistic and p-value for Chi-squared test in R</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a><span class="fu">chisq.test</span>(<span class="at">x =</span> SHS_table, <span class="at">correct =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  SHS_table
X-squared = 152.6, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Conclusion to the hypothesis test</li>
</ol>
<p>We reject the null hypothesis that glucose tolerance and diabetes are not associated (<span class="math inline">\(p&lt;2.2\cdot10^{-16}\)</span>). There is sufficient evidence that glucose tolerance and diabetes incidence are associated among American Indians.</p>
</div></div>
</section></section>
<section>
<section id="learning-objectives-7" class="title-slide slide level1 center">
<h1>Learning Objectives</h1>
<ol type="1">
<li><p>Recognize the motivation for and focus of our course (categorical responses)</p></li>
<li><p>Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation</p></li>
<li><p>Estimate a single proportion</p></li>
<li><p>Estimate a difference in proportions</p></li>
<li><p>Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test</p></li>
</ol>
<div class="lob">
<ol start="7" type="1">
<li>Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test</li>
</ol>
</div>
<ol start="8" type="1">
<li><p>Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test</p></li>
<li><p>Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test</p></li>
</ol>
</section>
<section id="fishers-exact-test" class="slide level2">
<h2>Fisher’s Exact Test</h2>
<ul>
<li>Only necessary when expected counts in one or more cells is less than 5</li>
<li>Given row and column totals fixed, computes exact probability that we observe our data or more extreme data</li>
<li>Consider a general 2 x 2 table:</li>
</ul>

<img data-src="./images/fisher_tab.png" class="quarto-figure quarto-figure-center r-stretch"><ul>
<li>The exact probability of observing a table with cells (a, b, c, d) can be computed based on the hypergeometric distribution</li>
</ul>
<p><span class="math display">\[P(a, b, c, d) = \dfrac{(a+b)!\cdot(c+d)!\cdot(a+c)!\cdot(b+d)!}{n!\cdot a!\cdot b!\cdot c!\cdot d!}\]</span></p>
<ul>
<li>Numerator is fixed and denominator changes</li>
</ul>
</section>
<section id="fishers-exact-test-process" class="slide level2">
<h2>Fisher’s Exact test: Process</h2>
<ol type="1">
<li><p>Check the <span style="color:#70AD47"><strong>expected cell counts</strong></span></p></li>
<li><p>Set the <span style="color:#70AD47"><strong>level of significance</strong></span> <span class="math inline">\(\alpha\)</span></p></li>
<li><p>Specify the <span style="color:#70AD47"><strong>null</strong></span> ( <span class="math inline">\(H_0\)</span> ) and <span style="color:#70AD47"><strong>alternative</strong></span> ( <span class="math inline">\(H_A\)</span> ) <span style="color:#70AD47"><strong>hypotheses</strong></span></p>
<ul>
<li>In symbols</li>
<li>In words</li>
<li>Alternative: one- or two-sided?</li>
</ul></li>
<li><p>Calculate the <span style="color:#70AD47"><strong>test statistic</strong></span> and <span style="color:#70AD47"><strong>p-value</strong></span> for Fisher Exact test in R</p>
<ul>
<li>We will not discuss the test statistic’s equation</li>
</ul></li>
<li><p>Write a <span style="color:#70AD47"><strong>conclusion</strong></span> to the hypothesis test</p>
<ul>
<li>Do we reject or fail to reject <span class="math inline">\(H_0\)</span>?</li>
<li>Write a conclusion in the context of the problem</li>
</ul></li>
</ol>
</section>
<section id="fishers-exact-test-postop-neuropathy-in-gender-affirming-care-12" class="slide level2">
<h2>Fisher’s Exact test: Postop neuropathy in gender affirming care (1/2)</h2>
<ul>
<li>Study on new postoperative neuropathy after receiving gender affirming care (<a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC10686520/">Study link</a>)
<ul>
<li>Postop neuropathy = nerve damage following surgery</li>
</ul></li>
<li>Study comprised of 232 trans men and trans women receiving their respective hormone therapies</li>
<li>They measured different aspects of the surgery to see if there was an association with development of postop neuropathy</li>
<li><strong>Goal in this example:</strong> see if estimated blood loss, greater than or less than 250 ml, is associated with postop neuropathy</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="odsmoqetfv" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#odsmoqetfv table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#odsmoqetfv thead, #odsmoqetfv tbody, #odsmoqetfv tfoot, #odsmoqetfv tr, #odsmoqetfv td, #odsmoqetfv th {
  border-style: none;
}

#odsmoqetfv p {
  margin: 0;
  padding: 0;
}

#odsmoqetfv .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 45px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 3px;
  border-top-color: #D5D5D5;
  border-right-style: solid;
  border-right-width: 3px;
  border-right-color: #D5D5D5;
  border-bottom-style: solid;
  border-bottom-width: 3px;
  border-bottom-color: #D5D5D5;
  border-left-style: solid;
  border-left-width: 3px;
  border-left-color: #D5D5D5;
}

#odsmoqetfv .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#odsmoqetfv .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#odsmoqetfv .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#odsmoqetfv .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#odsmoqetfv .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D5D5D5;
}

#odsmoqetfv .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D5D5D5;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D5D5D5;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#odsmoqetfv .gt_col_heading {
  color: #FFFFFF;
  background-color: #004D80;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#odsmoqetfv .gt_column_spanner_outer {
  color: #FFFFFF;
  background-color: #004D80;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#odsmoqetfv .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#odsmoqetfv .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#odsmoqetfv .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D5D5D5;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#odsmoqetfv .gt_spanner_row {
  border-bottom-style: hidden;
}

#odsmoqetfv .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D5D5D5;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D5D5D5;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#odsmoqetfv .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D5D5D5;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D5D5D5;
  vertical-align: middle;
}

#odsmoqetfv .gt_from_md > :first-child {
  margin-top: 0;
}

#odsmoqetfv .gt_from_md > :last-child {
  margin-bottom: 0;
}

#odsmoqetfv .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #89D3FE;
  border-left-style: solid;
  border-left-width: 1px;
  border-left-color: #89D3FE;
  border-right-style: solid;
  border-right-width: 1px;
  border-right-color: #89D3FE;
  vertical-align: middle;
  overflow-x: hidden;
}

#odsmoqetfv .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #5F5F5F;
  padding-left: 5px;
  padding-right: 5px;
}

#odsmoqetfv .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#odsmoqetfv .gt_row_group_first td {
  border-top-width: 2px;
}

#odsmoqetfv .gt_row_group_first th {
  border-top-width: 2px;
}

#odsmoqetfv .gt_summary_row {
  color: #333333;
  background-color: #89D3FE;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#odsmoqetfv .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D5D5D5;
}

#odsmoqetfv .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#odsmoqetfv .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D5D5D5;
}

#odsmoqetfv .gt_grand_summary_row {
  color: #FFFFFF;
  background-color: #00A1FF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#odsmoqetfv .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D5D5D5;
}

#odsmoqetfv .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D5D5D5;
}

#odsmoqetfv .gt_striped {
  background-color: #F4F4F4;
}

#odsmoqetfv .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D5D5D5;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D5D5D5;
}

#odsmoqetfv .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#odsmoqetfv .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#odsmoqetfv .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#odsmoqetfv .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#odsmoqetfv .gt_left {
  text-align: left;
}

#odsmoqetfv .gt_center {
  text-align: center;
}

#odsmoqetfv .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#odsmoqetfv .gt_font_normal {
  font-weight: normal;
}

#odsmoqetfv .gt_font_bold {
  font-weight: bold;
}

#odsmoqetfv .gt_font_italic {
  font-style: italic;
}

#odsmoqetfv .gt_super {
  font-size: 65%;
}

#odsmoqetfv .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#odsmoqetfv .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#odsmoqetfv .gt_indent_1 {
  text-indent: 5px;
}

#odsmoqetfv .gt_indent_2 {
  text-indent: 10px;
}

#odsmoqetfv .gt_indent_3 {
  text-indent: 15px;
}

#odsmoqetfv .gt_indent_4 {
  text-indent: 20px;
}

#odsmoqetfv .gt_indent_5 {
  text-indent: 25px;
}

#odsmoqetfv .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#odsmoqetfv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="gt_col_headings gt_spanner_row header">
<th rowspan="2" id="a::stub" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">EBL &gt; 250ml</th>
<th colspan="2" id="Postoperative Neuropathy" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" scope="colgroup"><div class="gt_column_spanner">
Postoperative Neuropathy
</div></th>
<th rowspan="2" id="Total" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Total</th>
</tr>
<tr class="gt_col_headings even">
<th id="No" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">No</th>
<th id="Yes" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Yes</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td id="stub_1_1" class="gt_row gt_left gt_stub" data-quarto-table-cell-role="th" scope="row">No</td>
<td class="gt_row gt_right" headers="stub_1_1 No">145</td>
<td class="gt_row gt_right" headers="stub_1_1 Yes">4</td>
<td class="gt_row gt_right" headers="stub_1_1 Total">149</td>
</tr>
<tr class="even">
<td id="stub_1_2" class="gt_row gt_left gt_stub" data-quarto-table-cell-role="th" scope="row">Yes</td>
<td class="gt_row gt_right gt_striped" headers="stub_1_2 No">78</td>
<td class="gt_row gt_right gt_striped" headers="stub_1_2 Yes">5</td>
<td class="gt_row gt_right gt_striped" headers="stub_1_2 Total">83</td>
</tr>
<tr class="odd">
<td id="stub_1_3" class="gt_row gt_left gt_stub" data-quarto-table-cell-role="th" scope="row">Total</td>
<td class="gt_row gt_right" headers="stub_1_3 No">223</td>
<td class="gt_row gt_right" headers="stub_1_3 Yes">9</td>
<td class="gt_row gt_right" headers="stub_1_3 Total">232</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="fishers-exact-test-postop-neuropathy-in-gender-affirming-care-22" class="slide level2">
<h2>Fisher’s Exact test: Postop neuropathy in gender affirming care (2/2)</h2>
<div class="columns">
<div class="column" style="width:40%;">
<ol type="1">
<li>Check expected cell counts threshold</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a><span class="fu">expected</span>(GAC_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     
             No      Yes
  No  143.21983 5.780172
  Yes  79.78017 3.219828</code></pre>
</div>
</div>
<p>One cell has an expected count less than 5</p>
<ol start="2" type="1">
<li><p><span class="math inline">\(\alpha = 0.05\)</span></p></li>
<li><p>Hypothesis test:</p>
<ul>
<li><span class="math inline">\(H_0\)</span> : There is no association between glucose tolerance and diabetes</li>
<li><span class="math inline">\(H_1\)</span> : There is an association between glucose tolerance and diabetes</li>
</ul></li>
</ol>
</div><div class="column" style="width:60%;">
<ol start="4" type="1">
<li>Calculate the test statistic and p-value for Fisher Exact test</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="fu">fisher.test</span>(<span class="at">x =</span> GAC_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  GAC_table
p-value = 0.2877
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
  0.4829292 12.0164676
sample estimates:
odds ratio 
  2.314727 </code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Conclusion to the hypothesis test</li>
</ol>
<p>We fail to reject the null hypothesis that estimated blood loss and postop neuropathy are not associated (<span class="math inline">\(p=0.29\)</span>). There is insufficient evidence that estimated blood loss and postop neuropathy are associated.</p>
</div></div>
</section></section>
<section>
<section id="learning-objectives-8" class="title-slide slide level1 center">
<h1>Learning Objectives</h1>
<ol type="1">
<li><p>Recognize the motivation for and focus of our course (categorical responses)</p></li>
<li><p>Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation</p></li>
<li><p>Estimate a single proportion</p></li>
<li><p>Estimate a difference in proportions</p></li>
<li><p>Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test</p></li>
</ol>
<div class="lob">
<ol start="8" type="1">
<li>Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test</li>
</ol>
</div>
<ol start="9" type="1">
<li>Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test</li>
</ol>
</section>
<section id="test-of-trend" class="slide level2">
<h2>Test of Trend</h2>
<ul>
<li><p>If <span style="color:#70AD47; font-weight: bold;">one or both variables are ordinal</span>, a <span style="color:#70AD47; font-style: italic;">test of trend</span> may be of interest</p>
<ul>
<li>Treats ordinal variables as quantitative rather than qualitative (nominal scale)</li>
<li>Test of trend has greater power than the test of general association</li>
<li>You can use a test of general association for non-ordinal variables</li>
</ul></li>
</ul>
<p>&nbsp;</p>
<ul>
<li><p>Two tests of trend that we we learn:</p>
<ul>
<li><p><strong>Cochran-Armitage test</strong></p>
<ul>
<li>Tests association between a <em>binary</em> response and an <em>ordinal</em> explanatory variable</li>
</ul></li>
<li><p><strong>Mantel-Haenszel test</strong></p>
<ul>
<li>Test association between an <em>ordinal</em> response and an <em>ordinal</em> explanatory variable</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="cochran-armitage-test" class="slide level2">
<h2>Cochran-Armitage test</h2>
<ul>
<li>Cochran-Armitage test for trend will determine if there is association between a <span style="color:#70AD47; font-weight: bold;">binary response variable</span> and an <span style="color:#70AD47; font-weight: bold;">ordinal variable with 3 or more categories</span></li>
</ul>
<p>&nbsp;</p>
<ul>
<li><p>It will test the trend of the proportions over the ordinal variable</p>
<ul>
<li>Answers the question: Does the proportion of people with a “successful” outcome increase as the ordinal explanatory variable increases?</li>
</ul></li>
</ul>
<p>&nbsp;</p>
<ul>
<li>Cochran-Armitage test for trend is only suitable for 2 x C contingency tables</li>
</ul>
</section>
<section id="cochran-armitage-test-hypothesis-test" class="slide level2">
<h2>Cochran-Armitage test: Hypothesis Test</h2>
<div class="columns">
<div class="column">
<div class="definition">
<div class="def-title">
<p>Null Hypothesis (<span class="math inline">\(H_0\)</span>)</p>
</div>
<div class="def-cont">
<p>The proportions of successes are the same across all C ordinal values of the explanatory variable. <span class="math display">\[p_1 = p_2 = ... = p_C\]</span></p>
</div>
</div>
</div><div class="column">
<div class="proof1">
<div class="proof-title">
<p>Alternative Hypothesis (<span class="math inline">\(H_1\)</span>)</p>
</div>
<div class="proof-cont">
<p>The proportions of successes tend to increase as ordinal value of the explanatory variable increases</p>
<p><span class="math display">\[p_1 \leq p_2 \leq ... \leq p_C\]</span></p>
<p>OR</p>
<p>The proportions of successes tend to decrease as ordinal value of the explanatory variable increases</p>
<p><span class="math display">\[p_1 \geq p_2 \geq ... \geq p_C\]</span></p>
</div>
</div>
</div></div>
</section>
<section id="cochran-armitage-test-process" class="slide level2">
<h2>Cochran-Armitage test: Process</h2>
<ol type="1">
<li><p>Set the <span style="color:#70AD47"><strong>level of significance</strong></span> <span class="math inline">\(\alpha\)</span></p></li>
<li><p>Specify the <span style="color:#70AD47"><strong>null</strong></span> ( <span class="math inline">\(H_0\)</span> ) and <span style="color:#70AD47"><strong>alternative</strong></span> ( <span class="math inline">\(H_A\)</span> ) <span style="color:#70AD47"><strong>hypotheses</strong></span></p>
<ul>
<li>In symbols</li>
<li>In words</li>
<li>Alternative: one- or two-sided?</li>
</ul></li>
<li><p>Calculate the <span style="color:#70AD47"><strong>test statistic</strong></span> and <span style="color:#70AD47"><strong>p-value</strong></span> for Cochran-Armitage test in R</p>
<ul>
<li>We will not discuss the test statistic’s equation</li>
<li>Just know it follows a Normal distribution</li>
</ul></li>
<li><p>Write a <span style="color:#70AD47"><strong>conclusion</strong></span> to the hypothesis test</p>
<ul>
<li>Do we reject or fail to reject <span class="math inline">\(H_0\)</span>?</li>
<li>Write a conclusion in the context of the problem</li>
</ul></li>
</ol>
</section>
<section id="cochran-armitage-test-example-13" class="slide level2">
<h2>Cochran-Armitage test: Example (1/3)</h2>
<p>We are interested in learning the association between the development of breast cancer and age at first birth among people who have given birth</p>
<p>&nbsp; &nbsp; &nbsp; &nbsp;</p>

<img data-src="./images/Cancer_conting.png" class="quarto-figure quarto-figure-center r-stretch"><p>&nbsp; &nbsp;</p>
</section>
<section id="cochran-armitage-test-example-23" class="slide level2">
<h2>Cochran-Armitage test: Example (2/3)</h2>
<ul>
<li>Before we go into the hypothesis test procedure, we need to construct the contingency table in R</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a>Cancer <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">320</span>, <span class="dv">1206</span>, <span class="dv">1011</span>, <span class="dv">463</span>, <span class="dv">220</span>)</span>
<span id="cb22-2"><a></a>No_Cancer <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1422</span>, <span class="dv">4432</span>, <span class="dv">2893</span>, <span class="dv">1092</span>, <span class="dv">406</span>)</span>
<span id="cb22-3"><a></a>bscancer <span class="ot">=</span> <span class="fu">matrix</span> (<span class="fu">c</span>(Cancer, No_Cancer), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> T)</span>
<span id="cb22-4"><a></a><span class="fu">rownames</span>(bscancer) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Cancer"</span>,<span class="st">"No Cancer"</span>)</span>
<span id="cb22-5"><a></a><span class="fu">colnames</span>(bscancer) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"&lt;20"</span>,<span class="st">"20-24"</span>,<span class="st">"25-29"</span>,<span class="st">"30-34"</span>,<span class="st">"&gt;=35"</span>)</span>
<span id="cb22-6"><a></a>bscancer</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           &lt;20 20-24 25-29 30-34 &gt;=35
Cancer     320  1206  1011   463  220
No Cancer 1422  4432  2893  1092  406</code></pre>
</div>
</div>
<ul>
<li>It does not need to be pretty to use in function</li>
</ul>
</section>
<section id="cochran-armitage-test-example-33" class="slide level2">
<h2>Cochran-Armitage test: Example (3/3)</h2>
<div class="columns">
<div class="column">
<ol type="1">
<li><p><span class="math inline">\(\alpha = 0.05\)</span></p></li>
<li><p>Hypothesis test:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The proportions of breast cancer are the same for all age levels of first birth. <span class="math display">\[p_1 = p_2 = ... = p_5\]</span></li>
<li><span class="math inline">\(H_1\)</span>: The proportions of breast cancer tends to increase as level of age of first birth increases</li>
</ul></li>
</ol>
<p><span class="math display">\[p_1 \leq p_2 \leq ... \leq p_5\]</span></p>
</div><div class="column">
<ol start="3" type="1">
<li>Calculate the test statistic and p-value for Cochran-Armitage test in R</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a><span class="fu">library</span>(DescTools)</span>
<span id="cb24-2"><a></a><span class="fu">CochranArmitageTest</span>(bscancer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Cochran-Armitage test for trend

data:  bscancer
Z = 11.358, dim = 5, p-value &lt; 2.2e-16
alternative hypothesis: two.sided</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Conclusion to the hypothesis test</li>
</ol>
<p>We reject the null hypothesis that proportions of breast cancer are the same for all age levels of first birth (<span class="math inline">\(p&lt;2.2\cdot10^{-16}\)</span>). There is sufficient evidence that the proportion of of breast cancer increase as the the age at first birth increases.</p>
</div></div>
</section></section>
<section>
<section id="learning-objectives-9" class="title-slide slide level1 center">
<h1>Learning Objectives</h1>
<ol type="1">
<li><p>Recognize the motivation for and focus of our course (categorical responses)</p></li>
<li><p>Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation</p></li>
<li><p>Estimate a single proportion</p></li>
<li><p>Estimate a difference in proportions</p></li>
<li><p>Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test</p></li>
<li><p>Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test</p></li>
</ol>
<div class="lob">
<ol start="9" type="1">
<li>Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test</li>
</ol>
</div>
</section>
<section id="mantel-haenszel-test" class="slide level2">
<h2>Mantel-Haenszel test</h2>
<ul>
<li><p>When both variables are ordinal, we can conduct Mantel-Haenszel test of trend for linear association</p></li>
<li><p>Mantel-Haenszel test for linear trend is suitable for any R x C contingency tables with two ordinal variables</p></li>
<li><p>Hypothesis test:</p></li>
</ul>
<div class="columns">
<div class="column">
<div class="definition">
<div class="def-title">
<p>Null Hypothesis (<span class="math inline">\(H_0\)</span>)</p>
</div>
<div class="def-cont">
<p>There is no correlation between the two variables <span class="math display">\[ \rho = 0\]</span></p>
</div>
</div>
</div><div class="column">
<div class="proof1">
<div class="proof-title">
<p>Alternative Hypothesis (<span class="math inline">\(H_1\)</span>)</p>
</div>
<div class="proof-cont">
<p>There is correlation between the two variables</p>
<p><span class="math display">\[ \rho \neq 0\]</span></p>
</div>
</div>
</div></div>
</section>
<section id="mantel-haenszel-test-process" class="slide level2">
<h2>Mantel-Haenszel test: Process</h2>
<ol type="1">
<li><p>Set the <span style="color:#70AD47"><strong>level of significance</strong></span> <span class="math inline">\(\alpha\)</span></p></li>
<li><p>Specify the <span style="color:#70AD47"><strong>null</strong></span> ( <span class="math inline">\(H_0\)</span> ) and <span style="color:#70AD47"><strong>alternative</strong></span> ( <span class="math inline">\(H_A\)</span> ) <span style="color:#70AD47"><strong>hypotheses</strong></span></p>
<ul>
<li>In symbols</li>
<li>In words</li>
<li>Alternative: one- or two-sided?</li>
</ul></li>
<li><p>Calculate the <span style="color:#70AD47"><strong>test statistic</strong></span> and <span style="color:#70AD47"><strong>p-value</strong></span> for Mantel-Haenszel test in R</p>
<ul>
<li>We will not discuss the test statistic’s equation</li>
</ul></li>
<li><p>Write a <span style="color:#70AD47"><strong>conclusion</strong></span> to the hypothesis test</p>
<ul>
<li>Do we reject or fail to reject <span class="math inline">\(H_0\)</span>?</li>
<li>Write a conclusion in the context of the problem</li>
</ul></li>
</ol>
</section>
<section id="mantel-haenszel-test-example-13" class="slide level2">
<h2>Mantel-Haenszel test: Example (1/3)</h2>
<p>A water treatment company is studying water additives and investigating how they affect clothes washing (through measurements of abrasions, wearing, and color loss).</p>
<p>The treatments studies where no treatment (plain water), the standard treatment, and a double dose of the standard treatment, called super. Washability was measured as low, medium and high.</p>
<p>Are levels of washability associated with treatment?</p>
<p>&nbsp;</p>

<img data-src="./images/water_conting.png" class="quarto-figure quarto-figure-center r-stretch"><p>&nbsp;</p>
</section>
<section id="mantel-haenszel-test-example-23" class="slide level2">
<h2>Mantel-Haenszel test: Example (2/3)</h2>
<ul>
<li>Before we go into the hypothesis test procedure, we need to construct the contingency table in R</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a>water <span class="ot">=</span> <span class="fu">matrix</span> (<span class="fu">c</span>(<span class="dv">27</span>, <span class="dv">14</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">17</span>, <span class="dv">26</span>, <span class="dv">5</span>, <span class="dv">12</span>, <span class="dv">50</span>), <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">byrow =</span> T)</span>
<span id="cb26-2"><a></a><span class="fu">rownames</span>(water) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"plain"</span>,<span class="st">"standard"</span>,<span class="st">"super"</span>)</span>
<span id="cb26-3"><a></a><span class="fu">colnames</span>(water) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"low"</span>,<span class="st">"medium"</span>,<span class="st">"high"</span>)</span>
<span id="cb26-4"><a></a>water</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         low medium high
plain     27     14    5
standard  10     17   26
super      5     12   50</code></pre>
</div>
</div>
<ul>
<li>It does not need to be pretty to use in function</li>
</ul>
</section>
<section id="mantel-haenszel-test-example-33" class="slide level2">
<h2>Mantel-Haenszel test: Example (3/3)</h2>
<div class="columns">
<div class="column">
<ol type="1">
<li><p><span class="math inline">\(\alpha = 0.05\)</span></p></li>
<li><p>Hypothesis test:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Water treatment and washability are not correlated. <span class="math display">\[ \rho = 0\]</span></li>
<li><span class="math inline">\(H_1\)</span>: Water treatment and washability are correlated.</li>
</ul></li>
</ol>
<p><span class="math display">\[ \rho \neq 0\]</span></p>
</div><div class="column">
<ol start="3" type="1">
<li>Calculate the test statistic and p-value for Mantel-Haenszel test in R</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a><span class="fu">library</span>(DescTools)</span>
<span id="cb28-2"><a></a><span class="fu">MHChisqTest</span>(water)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Mantel-Haenszel Chi-Square

data:  water
X-squared = 50.602, df = 1, p-value = 1.132e-12</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Conclusion to the hypothesis test</li>
</ol>
<p>We reject the null hypothesis that there is no correlation between washability and water treatment (<span class="math inline">\(p = 1.13 \cdot 10^{-12} &lt; 0.05\)</span>). There is sufficient evidence that level of water treatment is associated with washability.</p>
</div></div>
</section></section>
<section>
<section id="learning-objectives-10" class="title-slide slide level1 center">
<h1>Learning Objectives</h1>
<ol type="1">
<li><p>Recognize the motivation for and focus of our course (categorical responses)</p></li>
<li><p>Recall features of the Binomial distribution for categorical data analysis and utilize the normal approximation</p></li>
<li><p>Estimate a single proportion</p></li>
<li><p>Estimate a difference in proportions</p></li>
<li><p>Display data from two categorical variables, each with 2 or more categories, using R X C contingency tables</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Chi-squared test</p></li>
<li><p>Determine if a nominal response and nominal explanatory variable are associated with one another using the Fisher Exact test</p></li>
<li><p>Determine if a binary, nominal response and an ordinal explanatory variable are associated with one another using the Cochran-Armitage test</p></li>
<li><p>Determine if an ordinal response and ordinal explanatory variable are associated with one another using the Mantel-Haenszel test</p></li>
</ol>
</section>
<section id="more-resources" class="slide level2">
<h2>More resources</h2>
<ul>
<li><p><a href="https://nwakim.github.io/F24_EPI_525/schedule.html">Review from my EPI 525 class in F25</a></p>
<ul>
<li>Schedule from class: Lessons 15, 16, 19</li>
</ul></li>
<li><p><a href="https://niederhausen.github.io/BSTA_511_F23/weeks/week_07.html">For a refresher or review</a> of one proportion and differences in proportions</p>
<ul>
<li><p>And their power calculations</p></li>
<li><p>From Meike’s BSTA 511 course (see Day 12!)</p></li>
</ul></li>
<li><p><a href="https://niederhausen.github.io/BSTA_511_F23/weeks/week_08.html">For a refresher or review</a> of Chi-squared test or Fisher’s Exact test</p>
<ul>
<li>From Meike’s BSTA 511 course (see Day 13!)</li>
</ul></li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Lesson 2: Introduction to Categorical Data Analysis</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1955,

        height: 1100,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>