---
title: "Lessons"
date: "today"
format: 
  html:
    link-external-newwindow: true
    toc: true
    highlight-style: ayu
---

```{css, echo=FALSE}
.title{
  font-size: 40px;
  color: #C2352F;
  background-color: #fff;
  padding: 0px;
}

.description{
  font-size: 20px;
  color: #fff;
  background-color: #C2352F;
  padding: 10px;
}
```

+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lesson    | Topic                                                        | Slides                                                                                                                                                                                                                  |
+===========+==============================================================+:=======================================================================================================================================================================================================================:+
| 1         | File Organization within R                                   | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/01_File_Organization_R/01_File_Organization_R.qmd)]{style="color:#f8f5f0;"}                                                                                    |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2         | Introduction to Categorical Analysis                         | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/02_Intro_CDA/02_Intro_CDA.qmd)]{style="color:#f8f5f0;"}                                                                                                        |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3         | Measurement of Association for Contingency Tables            | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/03_Meas_Assoc_CT/03_Meas_Assoc_CT.qmd)]{style="color:#f8f5f0;"}                                                                                                |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4         | Measurements of Association and Agreement                    | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree.qmd)]{style="color:#f8f5f0;"}                                                                                          |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5         | Simple Logistic Regression                                   | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/05_Simple_logistic_reg/05_Simple_logistic_reg.qmd)]{style="color:#f8f5f0;"}                                                                                    |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 6         | Tests for GLMs using Likelihood function                     | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/06_Tests_GLMs/06_Tests_GLMs.qmd)]{style="color:#f8f5f0;"}                                                                                                      |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 7         | Predictions and Visualizations in Simple Logistic Regression | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/07_Pred_Viz/07_Pred_Viz.qmd)]{style="color:#f8f5f0;"}                                                                                                          |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 8         | Interpretations and Visualizations of Odds Ratios            | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/08_Interpretations_SLR/08_Interpretations_SLR.qmd)]{style="color:#f8f5f0;"}                                                                                    |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9         | Missing Data                                                 | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/09_Missing_data/09_Missing_data.pdf) [{{< iconify clarity group-solid size=29px >}}](/lectures/09_Missing_data/09_Activity_dogs.pptx)]{style="color:#f8f5f0;"} |
|           |                                                              |                                                                                                                                                                                                                         |
|           | Activity:                                                    |                                                                                                                                                                                                                         |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10        | Multiple Logistic Regression                                 | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/10_Multiple_logistic_regression/10_Multiple_logistic_regression.qmd)]{style="color:#f8f5f0;"}                                                                  |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11        | Interactions                                                 | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/11_Interactions/11_Interactions.qmd)]{style="color:#f8f5f0;"}                                                                                                  |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12        | Assessing Model Fit                                          | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/12_Assessing_fit/12_Assessing_fit.qmd)]{style="color:#f8f5f0;"}                                                                                                |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 13        | Numerical Problems                                           | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/13_Numeric_Problems/13_Numeric_problems.qmd)]{style="color:#f8f5f0;"}                                                                                          |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14        | Model Diagnostics                                            | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/14_Model_diagnostics/14_Model_diagnostics.qmd)]{style="color:#f8f5f0;"}                                                                                        |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 15        | Model Building                                               | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/15_Model_building/15_Model_Building.qmd)]{style="color:#f8f5f0;"}                                                                                              |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 16        | Poisson Regression                                           | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/16_Poisson_regression/16_Poisson_regression.qmd)]{style="color:#f8f5f0;"}                                                                                      |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 17        | Other types of categorical regressions!                      | [[{{< iconify ri slideshow-fill size=30px >}}](/lectures/17_Wrap_up/17_Wrap_up.qmd)]{style="color:#f8f5f0;"}                                                                                                            |
+-----------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```{r}
#| echo: false

g=3
```
