---
title: "Schedule"
date: "today"
format: 
  html:
    page-layout: full
    link-external-newwindow: true
    toc: true
    highlight-style: ayu
---

| Week | Date | Les-son | Topic | Key Info | Slides HTML | Slides PDF | Slides Notes | Exit tix | Echo 360 | Muddy Points |
|-------|-------|-------|-------|:-----:|:-----:|:-----:|:------------:|:-----:|:-----:|:-------------:|
| 1 | 3/31 | 1 | Welcome | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/01_Intro/01_Intro_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/01_Intro/01_Intro.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/01_Intro/01_Intro.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQUZMWVlJRkhZQjFJM1VNN1NKU0FLOFRTVy4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-03-31T13:00:00.000_2025-03-31T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | 2 | Introduction to Categorical Analysis |  | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/02_Intro_CDA/02_Intro_CDA.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/02_Intro_CDA/02_Intro_CDA.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/02_Intro_CDA/02_Intro_CDA_notes.pdf)]{style="color:#f8f5f0;"} |  |  | [[{{< iconify pajamas question size=30px >}}](/lessons/02_Intro_CDA/02_Intro_CDA_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | 4/2 | 3 | Measurement of Association for Contingency Tables | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/03_Meas_Assoc_CT/03_Meas_Assoc_CT_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/03_Meas_Assoc_CT/03_Meas_Assoc_CT.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/03_Meas_Assoc_CT/03_Meas_Assoc_CT.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/03_Meas_Assoc_CT/03_Meas_Assoc_CT_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUNTI0SlAzWks5OVE5MzVBN0g3UlA2NEFaSC4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-04-02T13:00:00.000_2025-04-02T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/03_Meas_Assoc_CT/03_Meas_Assoc_CT_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  |  |  |  |  |  |  |  |  |  |
| 2 | 4/7 | 4 | Measurements of Association and Agreement | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURUVDNEVBNzhPRkRHRktTSTlDWjFZUjVTOS4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-04-07T13:00:00.000_2025-04-07T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/04_Meas_Assoc_Agree/04_Meas_Assoc_Agree_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | 4/9 | 5 | Simple Logistic Regression | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/05_Simple_logistic_reg/05_Simple_logistic_reg_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/05_Simple_logistic_reg/05_Simple_logistic_reg.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/05_Simple_logistic_reg/05_Simple_logistic_reg.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/05_Simple_logistic_reg/05_Simple_logistic_reg_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUNERIRVI2Qk1VNlg3VU84T0Q3MVRMRFc2Qi4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-04-09T13:00:00.000_2025-04-09T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/05_Simple_logistic_reg/05_Simple_logistic_reg_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**4/11**]{style="color:#5B9BD5;"} |  | [**Lab 1 due \@ 11 pm**]{style="color:#5B9BD5;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 3 | 4/14 | 6 | Interpretations and Visualizations of Odds Ratios | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/06_Interpretations_SLR/06_Interpretations_SLR_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/06_Interpretations_SLR/06_Interpretations_SLR.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/06_Interpretations_SLR/06_Interpretations_SLR.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/06_Interpretations_SLR/06_Interpretations_SLR_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQTJXTlg1VDZUUjZYVVk5VjNHMTAySEkxOC4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-04-14T13:00:00.000_2025-04-14T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/06_Interpretations_SLR/06_Interpretations_SLR_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | 4/16 | 7 | Predictions and Visualizations in Simple Logistic Regression | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/07_Pred_Viz/07_Pred_Viz_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/07_Pred_Viz/07_Pred_Viz.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/07_Pred_Viz/07_Pred_Viz.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/07_Pred_Viz/07_Pred_Viz_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUNTJPVExCTU5GWVNYMkJNQk1BNVpVWTZPVC4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-04-16T13:00:00.000_2025-04-16T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/07_Pred_Viz/07_Pred_Viz_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  |  | **Required in-person attendance:** Lab 1 Discussion |  | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/L01_Discussion/L01_Discussion.qmd)]{style="color:#f8f5f0;"} |  |  |  |  | [[{{< iconify pajamas question size=30px >}}](/lessons/L01_Discussion/L01_Discussion_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**4/18**]{style="color:#5B9BD5;"} |  | [**HW 1 due \@ 11 pm**]{style="color:#5B9BD5;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 4 | 4/21 | 8 | Tests for GLMs using Likelihood function | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/08_Tests_GLMs/08_Tests_GLMs_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/08_Tests_GLMs/08_Tests_GLMs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/08_Tests_GLMs/08_Tests_GLMs.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/08_Tests_GLMs/08_Tests_GLMs_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMkNPS0xCOTlQSUlZRlkxUVM4ODc3R04xOC4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-04-21T13:00:00.000_2025-04-21T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/08_Tests_GLMs/08_Tests_GLMs_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | 4/23 | 9 | Multiple Logistic Regression | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/09_Multiple_logistic_regression/09_Multiple_logistic_regression_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/09_Multiple_logistic_regression/09_Multiple_logistic_regression.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/09_Multiple_logistic_regression/09_Multiple_logistic_regression.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/09_Multiple_logistic_regression/09_Multiple_logistic_regression_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMUpCTkgwWDcyRzVDODFIVVBTWUNFREs4Ty4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-04-23T13:00:00.000_2025-04-23T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/09_Multiple_logistic_regression/09_Multiple_logistic_regression_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**4/23**]{style="color:#5B9BD5;"} |  | [**Quiz 1 opens at 3pm**]{style="color:#5B9BD5;"} |  |  |  |  |  |  |  |
|  | [**4/25**]{style="color:#5B9BD5;"} |  | [**Lab 2 due \@ 11 pm**]{style="color:#5B9BD5;"} |  |  |  |  |  |  |  |
|  | [**4/27**]{style="color:#5B9BD5;"} |  | [**Quiz 1 closes at 11pm**]{style="color:#5B9BD5;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 5 | 4/28 | 10 | Interactions | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/10_Interactions/10_Interactions_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/10_Interactions/10_Interactions.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/10_Interactions/10_Interactions.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/10_Interactions/10_Interactions_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUOVlRNE9ZT1NMSVQ3U1pCQU5QMDhCM0NSUi4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-04-28T13:00:00.000_2025-04-28T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/10_Interactions/10_Interactions_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | 4/30 |  | Interactions (continued from Monday) |  | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/10_Interactions/10_Interactions.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/10_Interactions/10_Interactions.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/10_Interactions/10_Interactions_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQlNPMkU4STdTNVVDVE04SU5VQ05UNThKNy4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-04-30T13:00:00.000_2025-04-30T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/10_Interactions/10_Interactions_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  |  | **Required in-person attendance:** Lab 2 Discussion | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/L02_Discussion/L02_Discussion.qmd)]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQlNPMkU4STdTNVVDVE04SU5VQ05UNThKNy4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-04-30T13:00:00.000_2025-04-30T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**5/2**]{style="color:#5B9BD5;"} |  | [**HW 2 due \@ 11 pm**]{style="color:#5B9BD5;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 6 | 5/5 | 11 | Numerical Problems | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/11_Numeric_Problems/11_Numeric_problems_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/11_Numeric_Problems/11_Numeric_problems.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/11_Numeric_Problems/11_Numeric_problems.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/11_Numeric_Problems/11_Numeric_problems_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUNkI2WTM3SFpCVVlTRjVUUkpGTENETTZCTi4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-05-05T13:00:00.000_2025-05-05T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/11_Numeric_Problems/11_Numeric_problems_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | 5/7 | 12 | Assessing Model Fit | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/12_Assessing_fit/12_Assessing_fit_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/12_Assessing_fit/12_Assessing_fit.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/12_Assessing_fit/12_Assessing_fit.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/12_Assessing_fit/12_Assessing_fit_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUOVBBNFRLMFVUTUkzUEdERVdINk1FWVc0RC4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-05-07T13:00:00.000_2025-05-07T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/12_Assessing_fit/12_Assessing_fit_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**5/9**]{style="color:#5B9BD5;"} |  | [**Lab 3 due \@ 11 pm**]{style="color:#5B9BD5;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 7 | 5/12 | 13 | Model Diagnostics | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/13_Model_diagnostics/13_Model_diagnostics_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/13_Model_diagnostics/13_Model_diagnostics.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/13_Model_diagnostics/13_Model_diagnostics.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/13_Model_diagnostics/13_Model_diagnostics_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMFJSUzNNUUhWNVRPOEU0R0tLOVpXOU00MC4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-05-12T13:00:00.000_2025-05-12T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/13_Model_diagnostics/13_Model_diagnostics_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  |  | **Required in-person attendance:** Lab 3 Discussion |  | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/L03_Discussion/L03_Discussion.qmd)]{style="color:#f8f5f0;"} |  |  |  |  |  |
|  | 5/14 | 14 | Model Building | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/14_Model_building/14_Model_Building_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/14_Model_building/14_Model_Building.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/14_Model_building/14_Model_Building.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/14_Model_building/14_Model_Building_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQ1BOUVJERTI2WFdFVlBJOVFXR0ozQkU2QS4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-05-14T13:00:00.000_2025-05-14T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/14_Model_building/14_Model_Building_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**5/14**]{style="color:#5B9BD5;"} |  | [**Quiz 2 opens at 3pm**]{style="color:#5B9BD5;"} | [[{{< iconify akar-icons info-fill size=30px >}}](quiz_info/quiz_02_info.qmd)]{style="color:#f8f5f0;"} |  |  |  |  |  |  |
|  | [**5/16**]{style="color:#5B9BD5;"} |  | [**HW 3 due \@ 11 pm**]{style="color:#5B9BD5;"} |  |  |  |  |  |  |  |
|  | [**5/18**]{style="color:#5B9BD5;"} |  | [**Quiz 2 closes at 11pm**]{style="color:#5B9BD5;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 8 | 5/19 |  | Class canceled |  |  |  |  |  |  |  |
|  | 5/21 | 15 | Other types of categorical regression | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/15_Other_regression/15_Other_regression_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/15_Other_regression/15_Other_regression.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/15_Other_regression/15_Other_regression.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/15_Other_regression/15_Other_regression_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQ1NHMlUzMEpXVEo3R0o4WjhNS1RDOVNRQS4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/S25_BSTA_513/Student_files/Recordings/15_Other_regression.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=jfWgt7)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/15_Other_regression/15_Other_regression_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**5/23**]{style="color:#5B9BD5;"} |  | [**Lab 4 due 11pm**]{style="color:#5B9BD5;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 9 | 5/26 |  | No class, Memorial Day |  |  |  |  |  |  |  |
|  | 5/28 | 16 | Log-binomial regression | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/16_Log_binom_reg/16_Log_binom_reg_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/16_Log_binom_reg/16_Log_binom_reg.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/16_Log_binom_reg/16_Log_binom_reg.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/16_Log_binom_reg/16_Log_binom_reg_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUOUJVSzJMS0s5S0ZQWVZGMlBVTVlMRFQwSS4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-05-28T13:00:00.000_2025-05-28T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/16_Log_binom_reg/16_Log_binom_reg_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  |  | **Required in-person attendance:** Lab 4 Discussion |  |  |  |  |  |  |  |
|  | [**5/28**]{style="color:#5B9BD5;"} |  | [**Quiz 3 opens at 3pm**]{style="color:#5B9BD5;"} | [[{{< iconify akar-icons info-fill size=30px >}}](quiz_info/quiz_03_info.qmd)]{style="color:#f8f5f0;"} |  |  |  |  |  |  |
|  | [**5/30**]{style="color:#5B9BD5;"} |  | [**HW 4 due 11 pm**]{style="color:#5B9BD5;"} |  |  |  |  |  |  |  |
|  | [**6/1**]{style="color:#5B9BD5;"} |  | [**Quiz 3 closes at 11pm**]{style="color:#5B9BD5;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 10 | 6/2 | 17 | Missing Data | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/17_Missing_data/17_Missing_data_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/17_Missing_data/17_Missing_data.pptx) [{{< iconify clarity group-solid size=29px >}}](/lessons/17_Missing_data/17_Activity_dogs.pptx)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/17_Missing_data/17_Missing_data.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/17_Missing_data/17_Missing_data_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUNjYxNUpHM0pTWDVSOTgyNjAwNUVIM1c5Qy4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-06-02T13:00:00.000_2025-06-02T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/17_Missing_data/17_Missing_data_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | 6/4 | 18 | Poisson regression | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/17_Poisson_regression/17_Poisson_regression_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/17_Poisson_regression/17_Poisson_regression.qmd)]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUOUI1OVhRNVlGSk41VkZJTlFRTU5EU0UwMyQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_955b8e82-4670-424a-a38d-ef76973a5ddd_1f512230-df7b-40f0-86b4-1d3d2e23478f_2025-06-04T13:00:00.000_2025-06-04T15:00:00.000/classroom)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  |  | Project Poster Guidelines |  | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/19_Poster_help/19_Poster_help.qmd)]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |  |  | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  |  |  |  |  |  |  |  |  |  |
| 11 | 6/9 |  | **Required in-person attendance:** Project Day!! |  |  |  |  |  |  |  |
|  | [**6/9**]{style="color:#5B9BD5;"} |  | [**Project due 11pm**]{style="color:#5B9BD5;"} |  |  |  |  |  |  |  |
|  | [**6/15**]{style="color:#5B9BD5;"} |  | [**All late coursework due 11pm**]{style="color:#5B9BD5;"} |  |  |  |  |  |  |  |

: {.striped .hover tbl-colwidths="\[6, 6, 6, 30, 6, 6, 6,6, 6\]"}
