---
title: "Homework 4"
subtitle: "BSTA 513/613"
author: "Your name here - update this!!!!"
description: "Due: Thursday May 23, 2024 at 11pm"
date-modified: "today"
date: "5/23/2024"
format: 
  html:
    link-external-newwindow: true
    toc: true
    self-contained: true
    embed-resources: true
---

```{=html}
<style>div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}</style>
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 4, fig.width = 6, fig.align = "center")

library(tidyverse)
library(rstatix)
library(broom)
library(gt)
library(janitor)
library(readxl)
library(gridExtra)
library(ggfortify)  # autoplot(model)
library(gtsummary)
library(describedata) # gladder()
library(haven)
library(here)
```

::: callout-caution
Nicky needs to edit
:::

## Purpose

This homework is designed to help you practice the following important skills and knowledge that we covered in Lesson 13, 15-16:

- Visually assessing observations for which the model does not fit well
- Other types of regression 
- Poisson regression
- Log-binomial
- Multinomial

## Directions

-   [Download the `.qmd` file here.](https://github.com/nwakim/BSTA_513_S25/blob/main/homework/HW_04.qmd)

-   You will need to download the datasets from our shared folder.

-   Please upload your homework to Sakai. Upload both your .qmd code file and the rendered .html file

    -   Please rename you homework as Lastname_Firstinitial_HW02.qmd. This will help organize the homeworks when the TAs grade them.

-   For each question, make sure to include all code and resulting output in the html file to support your answers

-   Show the work of your calculations using R code within a code chunk. Make sure that both your code and output are visible in the rendered html file. This is the default setting.

::: callout-tip
It is a good idea to try rendering your document from time to time as you go along! Note that rendering automatically saves your qmd file and rendering frequently helps you catch your errors more quickly.
:::

## Questions Part 1



## Questions Part 2

### Question 1

For each of the following outcomes, what type of regression would you use? Explain your answer.

#### Part a

Number of minutes of moderate-to-vigorous physical activity per week (range: 0 to 600+)

Which regression model is most appropriate?

a. Linear regression
b. Logistic regression
c. Log-binomial regression
d. Poisson regression
e. Multinomial logistic regression

#### Part b

Whether the participant meets CDC recommendations for weekly physical activity (Yes/No)

Which regression model is most appropriate?

a. Linear regression
b. Logistic regression
c. Log-binomial regression
d. Poisson regression
e. Multinomial logistic regression

#### Part c

Number of workouts the person completed in the past week (values: 0, 1, 2, ..., 14)

Which regression model is most appropriate?

a. Linear regression
b. Logistic regression
c. Log-binomial regression
d. Poisson regression
e. Multinomial logistic regression

#### Part d

Self-reported activity level: Sedentary, Moderately active, Highly active

Which regression model is most appropriate?

a. Linear regression
b. Logistic regression
c. Log-binomial regression
d. Poisson regression
e. Multinomial logistic regression

