{
  "hash": "75138517171a90f83420c9f79d632eb0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lesson 4: Measurements of Association and Agreement\"\nauthor: \"Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#C2352F\"\ndate: \"04/07/2025\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"Lesson 4: Measurements of Association and Agreement\"\n    html-math-method: mathjax\n    highlight-style: ayu\nexecute:\n  echo: true\n  freeze: auto  # re-render only when source changes\n---\n\n\n\n## Poll Everywhere Question 1\n\n# Learning Objectives\n\n1.  Identify cases when it is appropriate to use risk difference, relative risk, or odds ratios\n2.  Expand work on contingency tables to evaluate the agreement or reproducibility using Cohen’s Kappa\n\n\n\n::: {.cell}\n<style type=\"text/css\">\n.reveal code {\n  max-height: 80% !important;\n}\n</style>\n:::\n\n::: {.cell}\n\n:::\n\n\n\n## Last class\n\n-   Used contingency tables to test and measure association between two variables\n\n    -   Categorical outcome variable (Y)\n    -   One categorical explanatory variable (X) with groups 1 and 2\n\n-   We looked at risk difference, risk ratio, and odds ratio to measure association\n\n| Measure | Formula for Estimate |\n|-------------------|-----------------------------------|\n| Risk difference | $\\widehat{RD} = \\widehat{p}_1 - \\widehat{p}_1 = \\dfrac{n_{11}}{n_1} - \\dfrac{n_{21}}{n_2}$ |\n| Relative risk / risk ratio | $\\widehat{RR}=\\dfrac{\\widehat{p}_1}{\\widehat{p}_2} = \\dfrac{n_{11}/n_1}{n_{21}/n_2}$ |\n| Odds ratio | $\\widehat{OR}=\\frac{\\widehat{\\text{odds}}_1}{\\widehat{\\text{odds}}_2}=\\frac{{\\widehat{p}}_1/(1-{\\widehat{p}}_1)}{{\\widehat{p}}_2/(1-{\\widehat{p}}_2)}$ |\n\n-   Discussed how OR will be an important measurement in logistic regression\n\n## Our example with Strong Heart Study\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ksqvjrsaxo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ksqvjrsaxo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ksqvjrsaxo thead, #ksqvjrsaxo tbody, #ksqvjrsaxo tfoot, #ksqvjrsaxo tr, #ksqvjrsaxo td, #ksqvjrsaxo th {\n  border-style: none;\n}\n\n#ksqvjrsaxo p {\n  margin: 0;\n  padding: 0;\n}\n\n#ksqvjrsaxo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 45px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 3px;\n  border-top-color: #D5D5D5;\n  border-right-style: solid;\n  border-right-width: 3px;\n  border-right-color: #D5D5D5;\n  border-bottom-style: solid;\n  border-bottom-width: 3px;\n  border-bottom-color: #D5D5D5;\n  border-left-style: solid;\n  border-left-width: 3px;\n  border-left-color: #D5D5D5;\n}\n\n#ksqvjrsaxo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ksqvjrsaxo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ksqvjrsaxo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ksqvjrsaxo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ksqvjrsaxo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D5D5D5;\n}\n\n#ksqvjrsaxo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D5D5D5;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D5D5D5;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ksqvjrsaxo .gt_col_heading {\n  color: #FFFFFF;\n  background-color: #004D80;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ksqvjrsaxo .gt_column_spanner_outer {\n  color: #FFFFFF;\n  background-color: #004D80;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ksqvjrsaxo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ksqvjrsaxo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ksqvjrsaxo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D5D5D5;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ksqvjrsaxo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ksqvjrsaxo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D5D5D5;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D5D5D5;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ksqvjrsaxo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D5D5D5;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D5D5D5;\n  vertical-align: middle;\n}\n\n#ksqvjrsaxo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ksqvjrsaxo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ksqvjrsaxo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #89D3FE;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #89D3FE;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #89D3FE;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ksqvjrsaxo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #5F5F5F;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ksqvjrsaxo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ksqvjrsaxo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ksqvjrsaxo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ksqvjrsaxo .gt_summary_row {\n  color: #333333;\n  background-color: #89D3FE;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ksqvjrsaxo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D5D5D5;\n}\n\n#ksqvjrsaxo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ksqvjrsaxo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D5D5D5;\n}\n\n#ksqvjrsaxo .gt_grand_summary_row {\n  color: #FFFFFF;\n  background-color: #00A1FF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ksqvjrsaxo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D5D5D5;\n}\n\n#ksqvjrsaxo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D5D5D5;\n}\n\n#ksqvjrsaxo .gt_striped {\n  background-color: #F4F4F4;\n}\n\n#ksqvjrsaxo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D5D5D5;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D5D5D5;\n}\n\n#ksqvjrsaxo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ksqvjrsaxo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ksqvjrsaxo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ksqvjrsaxo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ksqvjrsaxo .gt_left {\n  text-align: left;\n}\n\n#ksqvjrsaxo .gt_center {\n  text-align: center;\n}\n\n#ksqvjrsaxo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ksqvjrsaxo .gt_font_normal {\n  font-weight: normal;\n}\n\n#ksqvjrsaxo .gt_font_bold {\n  font-weight: bold;\n}\n\n#ksqvjrsaxo .gt_font_italic {\n  font-style: italic;\n}\n\n#ksqvjrsaxo .gt_super {\n  font-size: 65%;\n}\n\n#ksqvjrsaxo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ksqvjrsaxo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ksqvjrsaxo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ksqvjrsaxo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ksqvjrsaxo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ksqvjrsaxo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ksqvjrsaxo .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ksqvjrsaxo .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ksqvjrsaxo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"a::stub\">Glucose tolerance</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"Diabetes\">\n        <div class=\"gt_column_spanner\">Diabetes</div>\n      </th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"Total\">Total</th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a0\">No</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a1\">Yes</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Impaired</th>\n<td headers=\"stub_1_1 0\" class=\"gt_row gt_right\">334</td>\n<td headers=\"stub_1_1 1\" class=\"gt_row gt_right\">198</td>\n<td headers=\"stub_1_1 Total\" class=\"gt_row gt_right\">532</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Normal</th>\n<td headers=\"stub_1_2 0\" class=\"gt_row gt_right gt_striped\">1004</td>\n<td headers=\"stub_1_2 1\" class=\"gt_row gt_right gt_striped\">128</td>\n<td headers=\"stub_1_2 Total\" class=\"gt_row gt_right gt_striped\">1132</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Total</th>\n<td headers=\"stub_1_3 0\" class=\"gt_row gt_right\">1338</td>\n<td headers=\"stub_1_3 1\" class=\"gt_row gt_right\">326</td>\n<td headers=\"stub_1_3 Total\" class=\"gt_row gt_right\">1664</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n| Measure | Formula | Interpretation |\n|------------|--------------------|------------------------------------------|\n| Risk difference | $\\widehat{RD} = \\widehat{p}_1 - \\widehat{p}_1$ | The diabetes diagnosis risk difference between impaired and normal glucose tolerance is 0.2591 (95% CI: 0.2141, 0.3041). |\n| Relative risk / risk ratio | $\\widehat{RR}=\\dfrac{\\widehat{p}_1}{\\widehat{p}_2} = \\dfrac{n_{11}/n_1}{n_{21}/n_2}$ | The estimated risk of diabetes for American Indians with impaired glucose is 3.29 times the  with normal glucose tolerance (95% CI: 2.70, 4.01). |\n| Odds ratio | $\\widehat{OR}=\\frac{\\widehat{\\text{odds}}_1}{\\widehat{\\text{odds}}_2}=\\frac{{\\widehat{p}}_1/(1-{\\widehat{p}}_1)}{{\\widehat{p}}_2/(1-{\\widehat{p}}_2)}$ | The estimated odds of diabetes for American Indians with impaired glucose tolerance is 4.65 times the odds for American Indians with normal glucose tolerance. |\n\n# Learning Objectives\n\n::: lob\n1.  Identify cases when it is appropriate to use risk difference, relative risk, or odds ratios\n:::\n\n2.  Expand work on contingency tables to evaluate the agreement or reproducibility using Cohen’s Kappa\n\n## Relationship Between RR and OR (1/2)\n\n-   Notice that odds ratio is **not equivalent** to relative risk (or risk ratio)\n\n \n\n-   However, when the **probability of \"success\" is small** (e.g., rare disease), $\\widehat{OR}$ is a nice approximation of $\\widehat{RR}$ $$\\widehat{OR}=\\frac{{\\widehat{p}}_1/(1-{\\widehat{p}}_1)}{{\\widehat{p}}_2/(1-{\\widehat{p}}_2)}=\\widehat{RR}\\cdot \\frac{1-\\widehat{p_2}}{1-\\widehat{p_1}}$$\n\n    -   The fraction in the last term of the above expression approximately equals to 1.0 if $\\widehat{p}_1$ and $\\widehat{p}_2$ BOTH quite small (\\< 0.1)\n\n \n\n-   The $\\widehat{OR}$ and $\\widehat{RR}$ are not very close to each other in SHS: diabetes not a rare disease\n\n    -   $\\widehat{OR} = 4.65$\n    -   $\\widehat{RR} = 3.29$\n\n## Relationship Between RR and OR (2/2)\n\n-   An example where a disease rare over the whole sample (\\~1%), but ...\n\n    -   $\\widehat{OR}$ is not a good estimate of $\\widehat{RR}$ in “rare” disease\n\n![](./images/rare_dis.png){fig-align=\"center\"}\n\n-   $\\widehat{p}_1$ is 0.5: thus $\\widehat{OR}$ and $\\widehat{RR}$ are very different\n\n$$\\widehat{RR}=\\frac{0.5}{0.00102}=490 \\text{ and } \\widehat{OR} = \\frac{0.5(1-0.5)}{0.00102(1-0.00102)}=981$$\n\n## Poll Everywhere Question 2\n\n## RR in retrospective case-control study (1/3)\n\n-   In retrospective case-control studies: we **identify cases** (patients with the outcome), then select a number of controls (patients without the outcome)\n\n    -   Case-control study to require **much smaller sample size** than equivalent cohort studies\n\n    -   So we pick out the cases and controls first, **then see if there is exposure**\n\n \n\n-   However, the [proportion of cases in the sample]{style=\"color:#70AD47; font-weight: bold;\"} **does not** represent the [proportion of cases in the population]{style=\"color:#4472C4; font-weight: bold;\"}\n\n    -   RR compares probability of the outcome (case) for exposed and unexposed groups\n    -   Number of outcomes has been artificially inflated for case-control study\n\n## RR in retrospective case-control study (2/3)\n\n-   Assume a 1:2 case-control study summarized in below table:\n\n:::::: columns\n::: {.column width=\"15%\"}\n:::\n\n::: {.column width=\"70%\"}\n![](./images/retro_RR_tab1.png){fig-align=\"center\"}\n:::\n\n::: {.column width=\"15%\"}\n:::\n::::::\n\n-   Assume we compute the RR as if it is from a cohort study:\n\n$$\\widehat{RR}=\\frac{\\widehat{p_1}}{\\widehat{p_2}}=\\frac{n_{11}/n_{1+}}{n_{21}/n_{2+}}=\\frac{40/80}{60/220}=1.8333$$\n\n## RR in prospective cohort study\n\n-   In real world, the proportion of controls (not diseased) is typically much higher. Assume the table below shows the **proportion in the population in a cohort study**\n\n:::::: columns\n::: {.column width=\"15%\"}\n:::\n\n::: {.column width=\"70%\"}\n![](./images/retro_RR_tab2.png){fig-align=\"center\"}\n:::\n\n::: {.column width=\"15%\"}\n:::\n::::::\n\n-   The estimated RR for the patient population is:\n\n$$\\widehat{RR}=\\frac{\\widehat{p_1}}{\\widehat{p_2}}=\\frac{400/4400}{600/16600}=2.5152$$\n\n## Notes for Odds Ratios\n\n-   The OR is valid for\n\n    -   Case-control studies (where the RR is not appropriate)\n    -   Prospective cohort studies\n    -   Cross-sectional studies\n\n \n\n-   It can be interpreted either as...\n\n    -   Odds of **event** for exposed vs. unexposed individuals, or\n    -   Odds of **exposure** for individuals with vs. without the event of interest\n\n \n\n-   Pay attention to the numerator and denominator for the OR\n\n## OR in retrospective case-control study\n\n-   While we cannot estimate RR from a case-control study, we can still estimate OR for case-control study\n\n    -   OR does not require us to distinguish between the outcome variable and explanatory variable in the contingency table\n\n        -   AKA: Odds ratio of disease comparing exposed to not exposed is same as odds ratio of being exposed comparing diseased and not diseased\n\n \n\n::::: columns\n::: column\n-   For case-control study where the probability of having outcome is small, the $\\widehat{OR}$ is a nice approximation to $\\widehat{RR}$\n\n    -   For the 1:2 case-control table: $\\widehat{OR}=\\frac{40\\cdot160}{40\\cdot60} = 2.667$\n\n    -   Population cohort study: $\\widehat{RR}=2.5152$\n:::\n\n::: column\n![](./images/retro_RR_tab1.png){fig-align=\"center\"}\n:::\n:::::\n\n## Which measurement should one use?\n\n![](./images/meas_t.png){fig-align=\"center\"}\n\n# Learning Objectives\n\n1.  Identify cases when it is appropriate to use risk difference, relative risk, or odds ratios\n\n::: lob\n2.  Expand work on contingency tables to evaluate the agreement or reproducibility using Cohen’s Kappa\n:::\n\n## Measuring Agreement\n\n-   Still within the realm of contingency tables\n\n-   What if we are NOT looking at the association between two variables?\n\n \n\n-   What if we want to look at the agreement between two things?\n\n    -   Answers of same subjects for same survey taken at different times\n    -   Two different radiologists’ assessment of the same X-ray\n\n \n\n-   Cohen’s Kappa statistics: widely used as a measure of agreement\n\n    -   Example: Reliability studies, interobserver agreement\n\n## Poll Everywhere Question 3\n\n## Let's get our mood data down!\n\n:::::: columns\n::: {.column width=\"10%\"}\n:::\n\n::: {.column width=\"80%\"}\n![](./images/mood_ct.png){fig-align=\"center\"}\n:::\n\n::: {.column width=\"10%\"}\n:::\n::::::\n\n## Measuring Agreement\n\n-   If **perfect agreement** among the two raters/surveys:\n\n    -   We would expect nonzero entries only in the diagonal cells of the table\n\n \n\n-   $p_o$ is the observed proportion of complete agreement (concordance)\n\n-   $p_E$ is the expected proportion of complete agreement if the agreement is just due to chance\n\n-   If the $p_o$ is much greater than $p_E$, then the agreement level is high.\n\n    -   Otherwise, the agreement level is low\n\n \n\n:::::: columns\n::: {.column width=\"48%\"}\n-   **Cohen's Kappa** is based on the difference between $p_o$ and $p_E$: $$\\widehat{\\kappa}=\\frac{p_o-p_E}{1-p_E}$$\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n::: {.column width=\"48%\"}\n-   $\\widehat{\\kappa} = 0$: No agreement between surveys/raters other than what would be expected by chance\n-   $\\widehat{\\kappa} = 1$: Complete agreement\n:::\n::::::\n\n## Measuring Agreement: Cohen's Kappa\n\n::::::::: columns\n::: {.column width=\"52%\"}\n-   Point estimate: $$\\widehat{\\kappa}=\\frac{p_o-p_E}{1-p_E}$$\n\n    -   With $p_o=\\ \\frac{\\sum_{i}\\ n_{ii}}{n}$ (sum of diagonals divided by total)\n    -   With $p_E=\\sum_{i}{a_ib_i}$\n    -   With range of point estimate from $[-1, 1]$\n:::\n\n::: {.column width=\"4%\"}\n:::\n\n:::::: {.column width=\"44%\"}\n::::: definition\n::: def-title\nWhat’s $\\sum_{i}{a_ib_i}$?\n:::\n\n::: def-cont\nFor $i$ responses (row/columns), $a_i$ is proportion of $i$ response category in first survey and $b_i$ is proportion of $i$ response category in second survey (we'll show this in the example)\n:::\n:::::\n::::::\n:::::::::\n\n-   Approximate standard error:\n\n$$ SE_{\\widehat{\\kappa}} = \\sqrt{\\frac{1}{{n\\left(1-p_e\\right)}^2}\\left\\{p_e^2+p_e-\\sum_{i}\\left[a_ib_i\\left(a_i+b_i\\right)\\right]\\right\\}}$$\n\n-   95% Wald confidence interval for $\\widehat{\\kappa}$:\n\n$$\\widehat{\\kappa} \\pm 1.96 \\cdot SE_{\\widehat{\\kappa}}$$\n\n## Example: Our moods (1/3)\n\n:::::::: columns\n:::::: {.column width=\"68%\"}\n::::: example\n::: ex-title\nAgreement of surveys\n:::\n\n::: ex-cont\nCompute the point estimate and 95% confidence interval for the agreement between our Monday and Wednesday moods.\n:::\n:::::\n::::::\n\n::: {.column width=\"32%\"}\n![](./images/mood_ct.png){fig-align=\"center\"}\n:::\n::::::::\n\n**Needed steps:**\n\n1.  Compute the kappa statistic\n2.  Find confidence interval of kappa\n3.  Interpret the estimate\n\n## Example: Our moods (2/3)\n\n:::::::: columns\n:::::: {.column width=\"68%\"}\n::::: example\n::: ex-title\nAgreement of surveys\n:::\n\n::: ex-cont\nCompute the point estimate and 95% confidence interval for the agreement between our Monday and Wednesday moods.\n:::\n:::::\n::::::\n\n::: {.column width=\"32%\"}\n![](./images/mood_ct.png){fig-align=\"center\"}\n:::\n::::::::\n\n**Needed steps:**\n\n1/2. Compute the kappa statistic and find confidence interval of kappa\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(epiR)\nmoods = matrix(c(80, 80, 20, 20), nrow = 2, byrow = T)\nmoods\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1] [,2]\n[1,]   80   80\n[2,]   20   20\n```\n\n\n:::\n\n```{.r .cell-code}\nepi.kappa(moods, method = \"cohen\")$kappa \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  est         se      lower     upper\n1   0 0.07071068 -0.1385904 0.1385904\n```\n\n\n:::\n:::\n\n\n\n## Example: Our moods (3/3)\n\n:::::::: columns\n:::::: {.column width=\"68%\"}\n::::: example\n::: ex-title\nAgreement of surveys\n:::\n\n::: ex-cont\nCompute the point estimate and 95% confidence interval for the agreement between our Monday and Wednesday moods.\n:::\n:::::\n::::::\n\n::: {.column width=\"32%\"}\n![](./images/mood_ct.png){fig-align=\"center\"}\n:::\n::::::::\n\n**Needed steps:**\n\n3.  Interpret the estimate\n\nThe kappa statistic is \\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_ (95% CI: \\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_, \\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_), indicating \\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_ agreement.\n\nSince the 95% confidence interval does/does not contain 0, we have/do not have sufficient evidence that there is \\_\\_\\_\\_\\_\\_\\_\\_\\_ agreement between our mood on Monday and our mood on Wednesday.\n\n## Measuring Agreement: Oberved Kappas\n\n-   Guidelines for evaluating Kappa (Rosner TB)\n\n     \n\n    -   **Excellent agreement** if $\\widehat\\kappa \\geq 0.75$\n\n     \n\n    -   **Fair to good agreement** if $0.4 < \\widehat\\kappa < 0.75$\n\n     \n\n    -   **Poor agreement** if $\\widehat\\kappa \\leq 0.4$\n\n \n\nIf $\\widehat\\kappa<0$, suggest agreement less than by chance\n\n# Learning Objectives\n\n1.  Identify cases when it is appropriate to use risk difference, relative risk, or odds ratios\n2.  Expand work on contingency tables to evaluate the agreement or reproducibility using Cohen’s Kappa\n\n## Measurement of Association So Far\n\n-   Used contingency tables to test and measure association between two variables\n\n    -   Categorical outcome variable (Y)\n    -   One categorical explanatory variable (X)\n\n-   We looked at risk difference, risk ratio, and odds ratio to measure association\n\n-   Such an association is called crude association\n\n    -   No adjustment for possible confounding factors\n    -   Also called marginal association\n\n-   But we cannot expand analysis based on contingency tables past 3 variables\n\n    -   We can get into stratified contingency tables to bring in a 3rd variable\n    -   But I don't think it's worth it because regression can bring in (adjust for) many variables\n\n# Extra example in case the mood example fails beautifully\n\n## Just in case our data doesn't work out: Beef Consumption in Survey\n\nA diet questionnaire was mailed to 537 female American nurses on two separate occasions several months apart. The questions asked included the quantities eaten of more than 100 separate food items. The data from the two surveys for the amount of beef consumption are presented in the below table. How can reproducibility of response for the beef-consumption data be quantified?\n\n![](./images/beef.png){fig-align=\"center\"}\n\n## Example: Beef Consumption in Survey (1/3)\n\n:::::::: columns\n:::::: {.column width=\"62%\"}\n::::: example\n::: ex-title\nAgreement of surveys\n:::\n\n::: ex-cont\nCompute the point estimate and 95% confidence interval for the agreement between beef consumption surveys. Similar to question: Are results reproducible for the beef-consumption in the survey?\n:::\n:::::\n::::::\n\n::: {.column width=\"38%\"}\n![](./images/beef.png){fig-align=\"center\"}\n:::\n::::::::\n\n**Needed steps:**\n\n1.  Compute the kappa statistic\n2.  Find confidence interval of kappa\n3.  Interpret the estimate\n\n## Example: Beef Consumption in Survey (2/3)\n\n:::::::: columns\n:::::: {.column width=\"62%\"}\n::::: example\n::: ex-title\nAgreement of surveys\n:::\n\n::: ex-cont\nCompute the point estimate and 95% confidence interval for the agreement between beef consumption surveys. Similar to question: Are results reproducible for the beef-consumption in the survey?\n:::\n:::::\n::::::\n\n::: {.column width=\"38%\"}\n![](./images/beef.png){fig-align=\"center\"}\n:::\n::::::::\n\n**Needed steps:**\n\n1/2. Compute the kappa statistic and find confidence interval of kappa\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(epiR)\nbeef = matrix(c(136, 92, 69, 240), nrow = 2, byrow = T)\nepi.kappa(beef, method = \"cohen\")$kappa \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        est         se     lower     upper\n1 0.3781906 0.04100635 0.2978196 0.4585616\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n## Example: Beef Consumption in Survey (3/3)\n\n:::::::: columns\n:::::: {.column width=\"62%\"}\n::::: example\n::: ex-title\nAgreement of surveys\n:::\n\n::: ex-cont\nCompute the point estimate and 95% confidence interval for the agreement between beef consumption surveys. Similar to question: Are results reproducible for the beef-consumption in the survey?\n:::\n:::::\n::::::\n\n::: {.column width=\"38%\"}\n![](./images/beef.png){fig-align=\"center\"}\n:::\n::::::::\n\n**Needed steps:**\n\n3.  Interpret the estimate\n\nThe kappa statistic is 0.378 (95% CI: 0.298, 0.459), indicating fair agreement.\n\nSince the 95% confidence interval does not contain 0, we have sufficient evidence that there is fair agreement between the surveys for beef consumption. The survey is not reliably reproducible since we did not achieve excellent agreement.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}